"""Simplified Chinese and English site copy."""

ZH = {
    "chrome": {
        "brand_zh": "拼豆时光",
        "brand_en": "Fuse Beads",
        "nav_home": "官网",
        "nav_support": "支持",
        "nav_privacy": "隐私",
        "nav_open": "打开菜单",
        "nav_close": "关闭菜单",
        "nav_aria": "主导航",
        "skip": "跳到主要内容",
        "lang_aria": "语言",
        "cta_store": "在 App Store 下载",
        "footer_explore": "浏览",
        "footer_help": "帮助",
        "footer_legal": "法律",
        "footer_copy": "2026 上海岐山文化传播有限公司。拼豆时光 / Fuse Beads。屏幕颜色是近似值。Perler、Hama、Artkal 是各自权利人的商标。",
        "lost_title": "这页没有豆",
        "lost_body": "地址可能写错了。回到官网、支持或隐私政策。",
        "lost_home": "回官网",
    },
    "home": {
        "title": "拼豆时光：已上架的离线拼豆图纸应用",
        "description": "拼豆时光（Fuse Beads: Pattern Maker）已在 App Store 上架。把照片变成能烫出来的拼豆图纸：本机生成、逐颗编辑、材料统计、按颜色跟拼，导出 PNG 或 PDF。免费，无账号，不收集数据。",
        "live": "已在 App Store 上架",
        "hero_title": "把灵感放上豆板",
        "hero_lede": "拼豆时光是一款完全离线的 iPhone 拼豆图纸应用。选一张照片或内置图纸，在这台手机上生成可编辑图案、备料，再按颜色跟拼完成。",
        "cta_how": "看制作流程",
        "meta1": "无需账号",
        "meta2": "iOS 17 或更新",
        "meta3": "免费，无内购",
        "def_title": "这是什么应用",
        "def_body": "拼豆时光是上海岐山文化传播有限公司开发的 iPhone 应用，英文商店名为 Fuse Beads: Pattern Maker，Apple ID 6799906107，Bundle ID 为 com.weizhichao.beadday。它把相册或相机里的照片转成可对照实物豆板制作的图纸，也提供 24 款原创内置图案。生成、编辑、材料统计、跟拼和备份都在设备本地完成。应用不收集数据，不连接开发者服务器，也没有广告或分析 SDK。",
        "story_title": "先完成一张能烫出来的图纸",
        "story_body": "你选板尺寸、颜色上限，以及 Perler、Hama 或 Artkal 参考色板。应用在设备上用感知色差匹配颜色，并保住边缘。生成后可以逐颗改、看材料颗数，再按颜色勾选进度。",
        "story_alt": "亚麻桌上的柯基拼豆板、镊子、小碗和分格色豆",
        "loop_title": "从一张图到一板豆",
        "loop1_title": "选照片或内置图纸",
        "loop1_body": "用系统照片选择器、相机或文件取图，也可以从 24 款原创图纸开始。正方形裁切支持缩放和位移。智能背景移除默认关闭；开启后由 Apple Vision 在本机保护主体。",
        "loop2_title": "逐颗改到能做",
        "loop2_body": "点选颜色、空豆位橡皮擦、最多 30 步撤销，以及缩放和行列定位。材料页统计颗数、备齐勾选、包装余量，并可复制采购清单。",
        "loop2_alt": "逐颗编辑中的猫咪拼豆图纸",
        "loop3_title": "按颜色跟拼并导出",
        "loop3_body": "单色高亮、逐颗打勾、总体进度和下一颜色。可导出带行列坐标的 PNG 或 PDF；大图会分成 20×20 分区页。成品照也可以留在本地项目里。",
        "loop3_alt": "按颜色跟拼的小雏菊图纸",
        "spec_title": "对着实物板来的参数",
        "spec_body": "默认推荐 40×40、16 色。小物可以用 15×15 或 21×21。矩形和自定义尺寸会让裁切框跟豆板一致。",
        "spec_boards": "拼豆板",
        "spec_boards_val": "15、21、29、40、58，以及自定义",
        "spec_colors": "颜色上限",
        "spec_colors_val": "8、12、16、24 色",
        "spec_library": "内置图纸",
        "spec_library_val": "24 款原创图案",
        "spec_locales": "界面语言",
        "spec_locales_val": "13 种，含阿拉伯语 RTL",
        "spec_export": "导出",
        "spec_export_val": "PNG 与带坐标的 PDF",
        "pal_title": "色号只是屏幕参考",
        "pal_body": "应用内的 Perler 常用色名、Hama Midi 编号和 Artkal S-5mm 编号，用来选兼容的近似色板。商标归各自权利人。本应用与这些品牌没有隶属、赞助或官方授权关系。大量采购前请对照最新实物色卡。",
        "pal_perler": "Perler 常用色名",
        "pal_hama": "Hama Midi 编号",
        "pal_artkal": "Artkal S-5mm 编号",
        "locale_title": "语言跟着你走",
        "locale_body": "界面、权限说明和法律文案跟随系统语言，也可在应用内切换。阿拉伯语使用从右到左布局。本网站按语言分成独立地址，便于搜索和引用。",
        "off_title": "数据留在这台手机",
        "off1_title": "不收集",
        "off1_body": "没有账号、广告、第三方分析 SDK 或跨应用追踪。照片和项目不会被上传到开发者服务器。",
        "off2_title": "本机处理",
        "off2_body": "量化、背景移除、预览和备份都在 App 容器里完成。卸载会删除本地图纸，请先到设置导出备份。",
        "off3_title": "你决定离开的内容",
        "off3_body": "只有你保存 PNG 到照片，或用系统分享面板选择目标时，文件才会离开应用。",
        "cta_title": "在厨房桌上开始第一板",
        "cta_body": "现已在 App Store 免费下载。不需要注册。打开就能把一张照片变成可制作图纸。",
    },
    "support": {
        "title": "技术支持 · 拼豆时光",
        "description": "拼豆时光已上架。这里说明照片导入、图纸生成、材料、跟拼、备份、导出，以及如何写信给支持。应用完全离线，不收集数据。",
        "lead": "先看这些真实流程里的问题。若仍无法解决，写信到支持邮箱，并附上应用内复制的诊断信息。",
        "contact_title": "联系支持",
        "contact_body": "没有工单系统或承诺回复时限。公开支持页和邮箱是同一入口。",
        "contact_mail": "支持邮箱",
        "contact_include": "邮件请写明",
        "contact1": "App 版本（设置页可见）",
        "contact2": "iPhone 型号和 iOS 版本",
        "contact3": "复现步骤",
        "contact4": "设置里复制的诊断信息",
        "contact_note": "不要附带含私人内容的原始照片。诊断信息不包含照片或图纸内容。",
        "guides_title": "制作步骤",
        "g1_title": "把照片变成图纸",
        "g1_body": "在首页选择照片转图纸，用系统相册、相机或文件选图。先调裁切、板尺寸、颜色上限、细节模式和参考色板。默认高质量路径是 40×40、16 色。智能背景移除保持关闭，除非主体清晰且背景干扰大。看实时预览后生成，确认页可对比原图，或返回继续调参。",
        "g2_title": "统计材料并采购",
        "g2_body": "打开材料页查看每种颜色的颗数。勾选家里已有的颜色，按包装规格估算还缺几包，再复制采购清单。屏幕色号是近似参考，大量购买前请对照品牌最新实物色卡。",
        "g3_title": "按颜色跟拼",
        "g3_body": "在跟拼里选一个颜色，图纸会只高亮该色。点选已放上的豆位记录进度，查看总体完成度和下一颜色。需要时打开屏幕常亮。进度保存在本机项目中。",
        "g4_title": "导出与备份",
        "g4_body": "从工作区或项目菜单导出带行列坐标的 PNG 或 PDF。58×58 等大图会带 20×20 分区页。换机或卸载前，到「我的 → 设置与隐私」导出 JSON 备份。卸载会删除沙盒里的全部图纸。",
        "faq_title": "常见问题",
        "download_title": "到哪里下载",
        "download_body": "拼豆时光已在 App Store 上架，面向 iPhone，要求 iOS 17 或更新系统。免费，无内购和订阅。当前销售范围覆盖 175 个国家或地区。",
        "faqs": [
            ("照片会不会被上传？", "不会。你通过系统照片选择器、相机或文件提供的图片，只在设备上生成图纸。智能背景移除使用 Apple Vision 在本机工作，照片和遮罩都不会发送到服务器。"),
            ("为什么生成结果和我想的不一样？", "结果受原图清晰度、裁切、板尺寸、颜色上限和细节模式影响。默认高质量路径是 40×40、16 色。可先看实时预览，生成后在确认页对比原图，或返回继续调参。保存后也能用原图重新生成。"),
            ("智能背景移除怎么用？", "它默认关闭。打开后会在本机保护主体，并用连通背景判断空豆位。若边缘被切掉或背景仍在，关掉后再用手改空豆位，或换一张主体更清楚的照片。"),
            ("色号能直接拿去买豆吗？", "色号是屏幕近似参考，不能当成厂商官方精确颜色。显示器和材料批次都会有色差。大量采购前请对照品牌最新实物色卡。"),
            ("导出的 PNG 或 PDF 在哪里？", "从工作区或项目菜单导出。PNG 可保存到照片（只申请添加权限，不会读取图库）。PDF 可带行列坐标；58×58 等大图会包含 20×20 分区页。其他分享走系统分享面板。"),
            ("项目找不到了或打不开？", "数据在本机 Application Support/BeadTime。损坏项目会被隔离为 projects-invalid 文件，其余仍可打开。可先导出备份。若提示库文件过大，原文件会被隔离且不会覆盖。"),
            ("备份如何导入？", "设置里可导出版本化 JSON 备份，再导入合并。同一项目保留更新时间较新的版本。来自更新应用版本的备份无法导入。备份过大或项目过多也会被拒绝。"),
            ("卸载后数据还在吗？", "不在。卸载会删除沙盒里的图纸、预览和跟拼进度。换机或删除应用前，请先导出本地备份。"),
            ("如何复制诊断信息？", "打开我的 → 设置与隐私 → 复制诊断信息。内容包括 App 版本、设备、系统和本地项目数，不含照片或图纸。把它贴进支持邮件即可。"),
            ("支持哪些语言？", "英语、简体中文、繁体中文、日语、韩语、西班牙语、法语、德语、巴西葡萄牙语、意大利语、俄语、阿拉伯语（从右到左）和印地语。可跟随系统或在设置中固定。"),
            ("相机权限用来做什么？", "仅在你选择拍照生成图纸时使用。照片同样只在本机处理。应用不使用定位、麦克风、通讯录或跟踪权限。"),
            ("没有网络能用吗？", "能。核心功能完全离线。打开本支持站或发邮件才需要网络。应用本身不连接开发者服务器。"),
            ("应用是免费的吗？", "是。拼豆时光在 App Store 免费提供，没有内购、订阅或账号。打开即可制作。"),
            ("能在 iPad 或 Mac 上用吗？", "应用面向 iPhone，最低 iOS 17。App Store 分发未开放 iPad、Mac 或 Apple Vision Pro。请在 iPhone 上下载。"),
            ("开发者是谁？", "开发者是上海岐山文化传播有限公司（Shanghai Qishan Cultural Communication Co., Ltd.）。支持邮箱是 281916057@qq.com。"),
        ],
    },
    "privacy": {
        "title": "隐私政策 · 拼豆时光",
        "description": "拼豆时光不收集数据。照片、图纸和进度只在 iPhone 本地处理与保存。无账号、广告、分析或云同步。",
        "lead": "本政策说明拼豆时光实际上如何处理数据。应用已在 App Store 上架。它不收集数据，也不把内容发到开发者服务器。",
        "updated": "最近更新日期：2026年9月18日。实践与 2026年9月17日公开文本一致。本次更新把政策写成可独立抓取的网页，并写明应用已上架、网站不使用 cookie。",
        "toc_label": "本页目录",
        "toc": [
            ("#collect", "我们收集什么"),
            ("#photos", "照片与相机"),
            ("#storage", "本地存储"),
            ("#share", "分享与照片库"),
            ("#controls", "你的控制"),
            ("#children", "儿童"),
            ("#third", "第三方"),
            ("#contact", "更新与联系"),
        ],
        "sections": [
            (
                "collect",
                "我们收集什么",
                "不收集。开发者不会从本应用收集照片、图纸、材料清单、进度或使用记录。没有账号、广告、分析 SDK、崩溃上报、云同步或跨应用追踪。App Store 隐私标签的答案是：否，我们不从此 App 收集数据。隐私清单中的收集数据类型为空。UserDefaults 仅保存首次引导完成状态和语言偏好。",
            ),
            (
                "photos",
                "照片与相机",
                "你主动选择的相册图片、文件，或用系统相机拍摄的图片，只在设备上用于生成拼豆图纸。若开启智能移除背景，Apple Vision 在本机识别并保护主体；照片和遮罩不会发送给 Apple、开发者或任何服务器。应用会在容器内保存一份独立压缩预览，便于继续编辑和放入备份。",
            ),
            (
                "storage",
                "本地存储与保留",
                "项目元数据、豆位、材料备齐状态、跟拼进度和压缩预览保存在 App 沙盒的 Application Support/BeadTime，直到你删除单个项目、在设置中删除全部项目，或卸载应用。你可以随时导出本地备份、PNG 或 PDF。无效数据会被隔离，不会覆盖其余项目。",
            ),
            (
                "share",
                "保存到照片与分享",
                "点击“保存 PNG 到照片”时，应用只申请添加照片权限，写入你选择的导出图，不会用该权限读取图库。其他导出仅在你使用 iOS 分享面板并选择目标后离开设备。系统照片选择器和你选择的分享目标不属于开发者收集。",
            ),
            (
                "controls",
                "你的控制",
                "你可以只提供所选照片，随时删除项目或全部本地数据，并导出备份。本网站是只读静态页，不要求登录，不使用表单、cookie、分析、广告或数据库。语言通过页面地址区分。只有你主动发邮件时，支持邮箱才会收到你选择提供的内容。",
            ),
            (
                "children",
                "儿童与敏感信息",
                "应用不建设儿童账户，也不要求姓名、联系方式或其他敏感信息。建议年龄分级为 4+，并可用于亲子创作，但请不要导入你不希望保留在本地项目中的照片。我们不面向收集儿童个人信息。",
            ),
            (
                "third",
                "第三方与服务端",
                "应用没有第三方运行时 SDK，不连接开发者业务服务器。智能背景移除使用 iOS 自带的 Vision 框架，在设备上完成。本网站按文档托管时也不包含分析或广告脚本。邮件服务由你使用的邮箱提供商处理。",
            ),
            (
                "contact",
                "政策更新与联系",
                "若隐私实践发生实质变化，我们会更新本政策和日期。开发者：上海岐山文化传播有限公司（Shanghai Qishan Cultural Communication Co., Ltd.）。隐私问题请发送至 281916057@qq.com。",
            ),
        ],
    },
}

EN = {
    "chrome": {
        "brand_zh": "拼豆时光",
        "brand_en": "Fuse Beads",
        "nav_home": "Home",
        "nav_support": "Support",
        "nav_privacy": "Privacy",
        "nav_open": "Open menu",
        "nav_close": "Close menu",
        "nav_aria": "Primary",
        "skip": "Skip to content",
        "lang_aria": "Language",
        "cta_store": "Download on the App Store",
        "footer_explore": "Explore",
        "footer_help": "Help",
        "footer_legal": "Legal",
        "footer_copy": "2026 Shanghai Qishan Cultural Communication Co., Ltd. 拼豆时光 / Fuse Beads. Screen colors are approximations. Perler, Hama, and Artkal are trademarks of their owners.",
        "lost_title": "No beads on this page",
        "lost_body": "That address is not in the box. Head back to the site, support, or the privacy policy.",
        "lost_home": "Back to the site",
    },
    "home": {
        "title": "Fuse Beads: offline perler pattern app on the App Store",
        "description": "Fuse Beads: Pattern Maker is on the App Store. Turn a photo into an ironable fuse-bead pattern on your iPhone. Edit bead by bead, count materials, follow color by color, export PNG or PDF. Free. No account. No data collection.",
        "live": "On the App Store",
        "hero_title": "Place the idea on the pegboard",
        "hero_lede": "Fuse Beads is a fully offline iPhone studio for fuse-bead patterns. Choose a photo or a built-in design, generate an editable pattern on this phone, prepare beads, and finish color by color.",
        "cta_how": "See the making loop",
        "meta1": "No account",
        "meta2": "iOS 17 or later",
        "meta3": "Free, no in-app purchases",
        "def_title": "What this app is",
        "def_body": "Fuse Beads: Pattern Maker is an iPhone app from Shanghai Qishan Cultural Communication Co., Ltd. The Chinese name is 拼豆时光. Apple ID 6799906107. Bundle ID com.weizhichao.beadday. It turns a photo from Photos, the camera, or Files into a pattern you can place on a physical pegboard, and it includes 24 original presets. Generation, editing, material counts, guided making, and backups stay on the device. The app does not collect data, does not contact a developer server, and includes no ads or analytics SDK.",
        "story_title": "A pattern you can iron",
        "story_body": "You pick board size, color limit, and a Perler, Hama, or Artkal reference palette. Matching happens on the device with perceptual color difference and edge care. Then you edit bead by bead, check counts, and mark progress by color.",
        "story_alt": "A corgi fuse-bead board, tweezers, a bowl of beads, and a sorted tray on linen",
        "loop_title": "From one picture to one board",
        "loop1_title": "Start from a photo or a preset",
        "loop1_body": "Use the system photo picker, camera, or Files, or begin with 24 original presets. Square crop supports zoom and offset. Smart background removal stays off until you enable it. Apple Vision then protects the subject on the device.",
        "loop2_title": "Edit until it is makeable",
        "loop2_body": "Tap to recolor, erase empty cells, undo up to 30 steps, and jump by row and column. The material list covers counts, ready checkmarks, pack estimates, and a copyable shopping list.",
        "loop2_alt": "A cat bead pattern being edited bead by bead",
        "loop3_title": "Follow by color, then export",
        "loop3_body": "Highlight one color, check off beads, and see overall progress plus the next color. Export PNG or PDF with coordinates. Large boards split into 20×20 section pages. A finished photo can stay on the local project.",
        "loop3_alt": "A daisy pattern used for guided making",
        "spec_title": "Sizes that match physical boards",
        "spec_body": "The usual starting point is 40×40 with 16 colors. Small charms fit 15×15 or 21×21. Rectangles and custom sizes keep the crop frame matched to the board.",
        "spec_boards": "Boards",
        "spec_boards_val": "15, 21, 29, 40, 58, plus custom",
        "spec_colors": "Color limit",
        "spec_colors_val": "8, 12, 16, or 24 colors",
        "spec_library": "Built-in patterns",
        "spec_library_val": "24 original designs",
        "spec_locales": "Languages",
        "spec_locales_val": "13 locales, including Arabic RTL",
        "spec_export": "Export",
        "spec_export_val": "PNG and PDF with coordinates",
        "pal_title": "Color codes are on-screen references",
        "pal_body": "Perler common names, Hama Midi numbers, and Artkal S-5mm numbers help you pick a compatible approximate palette. Those trademarks belong to their owners. This app is not affiliated with, sponsored by, or officially authorized by those brands. Check a current physical chart before buying in quantity.",
        "pal_perler": "Perler common names",
        "pal_hama": "Hama Midi numbers",
        "pal_artkal": "Artkal S-5mm numbers",
        "locale_title": "The interface follows you",
        "locale_body": "UI, permission text, and legal copy follow the system language, or a language you lock in Settings. Arabic uses a right-to-left layout. This website uses a separate address for each language so search engines and assistants can cite the right page.",
        "off_title": "It stays on this phone",
        "off1_title": "Nothing collected",
        "off1_body": "No accounts, ads, third-party analytics SDKs, or tracking. The app does not upload photos or projects to a developer server.",
        "off2_title": "On-device work",
        "off2_body": "Quantization, background removal, previews, and backups live in the app container. Uninstalling deletes local patterns, so export a backup in Settings first.",
        "off3_title": "You choose what leaves",
        "off3_body": "Files leave the app only when you save a PNG to Photos or pick a destination in the system share sheet.",
        "cta_title": "Start the first board at the table",
        "cta_body": "Free on the App Store now. No sign-in. Open the app and turn a photo into a makeable pattern.",
    },
    "support": {
        "title": "Support · Fuse Beads",
        "description": "Help for Fuse Beads: Pattern Maker on the App Store. Photo import, generation, materials, follow-along, backups, export, and how to email support. The app is offline and collects no data.",
        "lead": "Start with questions from real product flows. If you still need help, email support and paste the in-app diagnostic text.",
        "contact_title": "Contact support",
        "contact_body": "There is no ticket system or reply-time promise. This page and the support inbox are the same door.",
        "contact_mail": "Support email",
        "contact_include": "Please include",
        "contact1": "App version from Settings",
        "contact2": "iPhone model and iOS version",
        "contact3": "Steps to reproduce",
        "contact4": "Diagnostic text copied in Settings",
        "contact_note": "Do not attach original photos that contain private content. Diagnostics omit photos and pattern content.",
        "guides_title": "How to make a board",
        "g1_title": "Turn a photo into a pattern",
        "g1_body": "On Home, start a photo-to-pattern project and pick an image from Photos, the camera, or Files. Set crop, board size, color limit, detail mode, and reference palette. A careful default is 40×40 with 16 colors. Leave smart background removal off unless the subject is clear and the background gets in the way. Watch the live preview, generate, then confirm against the original or go back and retune.",
        "g2_title": "Count materials and shop",
        "g2_body": "Open Materials to see bead counts by color. Tick colors you already have, estimate extra packs, and copy the shopping list. On-screen codes are approximate. Check the brand's current physical chart before a large purchase.",
        "g3_title": "Follow along by color",
        "g3_body": "In Follow, pick one color so the board highlights only that color. Tap placed beads to record progress, watch overall completion, and see the next color. Keep the screen awake if you need it. Progress stays in the local project.",
        "g4_title": "Export and back up",
        "g4_body": "Export PNG or PDF with coordinates from the workspace or project menu. Large boards such as 58×58 include 20×20 section pages. Before you change phones or delete the app, export a JSON backup from Me → Settings and Privacy. Uninstalling deletes every pattern in the sandbox.",
        "faq_title": "Common questions",
        "download_title": "Where to download",
        "download_body": "Fuse Beads: Pattern Maker is on the App Store for iPhone, iOS 17 or later. It is free, with no in-app purchases or subscriptions. It is sold in 175 countries or regions.",
        "faqs": [
            ("Are my photos uploaded?", "No. Photos you pick with the system picker, camera, or Files are processed only on the device. Smart background removal uses Apple Vision on the device. Photos and masks are not sent to a server."),
            ("Why does the pattern look off?", "Results depend on source sharpness, crop, board size, color limit, and detail mode. The usual quality path is 40×40 with 16 colors. Use the live preview, confirm against the original, or go back and retune. You can also regenerate from the original after saving."),
            ("How does smart background removal work?", "It is off by default. When enabled, it protects the subject on the device and treats connected background as empty cells. If edges vanish or background remains, turn it off and edit empty cells by hand, or use a clearer subject photo."),
            ("Can I buy beads from the on-screen codes?", "Treat codes as approximate screen references, not official factory matches. Displays and material batches vary. Compare the brand's current physical chart before a large purchase."),
            ("Where do PNG and PDF exports go?", "Export from the workspace or project menu. PNG can be saved to Photos with add-only access; the app does not read your library with that permission. PDFs include coordinates. Large boards such as 58×58 add 20×20 section pages. Other sharing uses the system share sheet."),
            ("A project is missing or will not open.", "Data lives in Application Support/BeadTime on the device. Damaged items are quarantined as projects-invalid files so the rest can open. Export a backup first. If the library file is too large, the original is set aside and not overwritten."),
            ("How do backups merge?", "Settings can export a versioned JSON backup and import it with merge. For the same project, the newer updated time wins. Backups from a newer app version cannot be imported. Oversized files or too many projects are rejected."),
            ("Does uninstalling keep my patterns?", "No. Uninstalling deletes sandbox patterns, previews, and progress. Export a local backup before you remove the app or change phones."),
            ("How do I copy diagnostics?", "Go to Me → Settings and Privacy → Copy Diagnostic Information. It includes app version, device, system, and local project count. It does not include photos or patterns. Paste it into your support email."),
            ("Which languages are included?", "English, Simplified Chinese, Traditional Chinese, Japanese, Korean, Spanish, French, German, Brazilian Portuguese, Italian, Russian, Arabic (right to left), and Hindi. Follow the system or lock a language in Settings."),
            ("Why does the app ask for the camera?", "Only when you choose to take a photo for a pattern. That photo is also processed on the device. The app does not use location, microphone, contacts, or tracking."),
            ("Does it work without a network?", "Yes. Core making is fully offline. You only need a network to open this site or send email. The app does not contact a developer server."),
            ("Is the app free?", "Yes. Fuse Beads is free on the App Store. There are no in-app purchases, subscriptions, or accounts. Open it and start a board."),
            ("Does it run on iPad or Mac?", "The app is built for iPhone on iOS 17 or later. iPad, Mac, and Apple Vision Pro are not listed App Store destinations. Download it on iPhone."),
            ("Who makes Fuse Beads?", "Shanghai Qishan Cultural Communication Co., Ltd. The Chinese name of the company is 上海岐山文化传播有限公司. Support email: 281916057@qq.com."),
        ],
    },
    "privacy": {
        "title": "Privacy Policy · Fuse Beads",
        "description": "Fuse Beads does not collect data. Photos, patterns, and progress stay on your iPhone. No account, ads, analytics, or cloud sync.",
        "lead": "This policy describes what Fuse Beads actually does with data. The app is on the App Store. It does not collect data and does not send your content to a developer server.",
        "updated": "Last updated: 18 September 2026. Practices match the public text dated 17 September 2026. This edition states that the app is live, publishes the policy as crawlable pages, and notes that the website does not use cookies.",
        "toc_label": "On this page",
        "toc": [
            ("#collect", "What we collect"),
            ("#photos", "Photos and camera"),
            ("#storage", "Local storage"),
            ("#share", "Photos and sharing"),
            ("#controls", "Your controls"),
            ("#children", "Children"),
            ("#third", "Third parties"),
            ("#contact", "Updates and contact"),
        ],
        "sections": [
            (
                "collect",
                "What we collect",
                "Nothing. The developer does not collect photos, patterns, material lists, progress, or usage records from the app. There is no account, advertising, analytics SDK, crash reporter, cloud sync, or cross-app tracking. The App Store privacy label says we do not collect data from this app. The privacy manifest lists no collected data types. UserDefaults stores onboarding completion and language preference only.",
            ),
            (
                "photos",
                "Photos and camera",
                "Photos you pick from the library or Files, or capture with the system camera, are used only on the device to build bead patterns. If Smart Background Removal is on, Apple Vision finds and protects the subject on the device. Photos and masks are not sent to Apple, the developer, or any server. The app keeps a separate compressed preview in its container for editing and backups.",
            ),
            (
                "storage",
                "Local storage and retention",
                "Project metadata, bead cells, material checkmarks, guided progress, and compressed previews stay in Application Support/BeadTime inside the sandbox until you delete a project, delete all projects in Settings, or uninstall the app. You can export a local backup, PNG, or PDF at any time. Invalid data is quarantined and does not overwrite other projects.",
            ),
            (
                "share",
                "Saving to Photos and sharing",
                "When you tap Save PNG to Photos, the app asks for add-only access and writes the export you chose. It does not use that permission to read your library. Other exports leave the device only through the iOS share sheet and the destination you pick. The system picker and the share destination you choose are not developer collection.",
            ),
            (
                "controls",
                "Your controls",
                "You can provide only selected photos, delete projects or all local data, and export backups at any time. This website is a read-only static site. It does not require sign-in and does not use forms, cookies, analytics, ads, or a database. Language is chosen by page address. The support inbox receives only what you choose to send.",
            ),
            (
                "children",
                "Children and sensitive information",
                "The app does not create child accounts and does not ask for names, contact details, or other sensitive information. The suggested age rating is 4+, and families may use it together. Do not import a photo whose contents you do not want stored in a local project. The app is not designed to collect children's personal information.",
            ),
            (
                "third",
                "Third parties and servers",
                "The app has no third-party runtime SDK and does not contact a developer backend. Smart background removal uses the on-device Vision framework included with iOS. This website, when hosted as documented, includes no analytics or ad scripts. Email is handled by the mail provider you use to write in.",
            ),
            (
                "contact",
                "Updates and contact",
                "If privacy practices change in a material way, we will update this policy and its date. Developer: Shanghai Qishan Cultural Communication Co., Ltd. For privacy questions, email 281916057@qq.com.",
            ),
        ],
    },
}
