"""German, French, Spanish, Italian, Portuguese (Brazil), and Russian site copy."""

DE = {
    "chrome": {
        "brand_zh": "拼豆时光",
        "brand_en": "Fuse Beads",
        "nav_home": "Start",
        "nav_support": "Hilfe",
        "nav_privacy": "Datenschutz",
        "nav_open": "Menü öffnen",
        "nav_close": "Menü schließen",
        "nav_aria": "Hauptnavigation",
        "skip": "Zum Inhalt",
        "lang_aria": "Sprache",
        "cta_store": "Im App Store laden",
        "footer_explore": "Entdecken",
        "footer_help": "Hilfe",
        "footer_legal": "Rechtliches",
        "footer_copy": "2026 Shanghai Qishan Cultural Communication Co., Ltd. 拼豆时光 / Fuse Beads. Bildschirmfarben sind Näherungen. Perler, Hama und Artkal sind Marken ihrer Inhaber.",
        "lost_title": "Keine Perlen auf dieser Seite",
        "lost_body": "Diese Adresse liegt nicht im Kasten. Zurück zur Seite, zur Hilfe oder zur Datenschutzerklärung.",
        "lost_home": "Zur Startseite",
    },
    "home": {
        "title": "Fuse Beads: Offline-Bügelperlen-App im App Store",
        "description": "Fuse Beads: Pattern Maker ist im App Store. Aus einem Foto wird eine bügelbare Vorlage auf dem iPhone. Perle für Perle ändern, Stückzahlen sehen, Farbe für Farbe folgen, PNG oder PDF exportieren. Kostenlos. Kein Konto. Keine Datenerhebung.",
        "live": "Im App Store",
        "hero_title": "Die Idee auf die Steckplatte",
        "hero_lede": "Fuse Beads ist eine vollständig offline laufende iPhone-App für Bügelperlen-Vorlagen. Wähle ein Foto oder eine eingebaute Vorlage, erzeuge auf diesem Gerät ein editierbares Muster, lege Perlen bereit und arbeite Farbe für Farbe weiter.",
        "cta_how": "Den Ablauf ansehen",
        "meta1": "Kein Konto",
        "meta2": "iOS 17 oder neuer",
        "meta3": "Kostenlos, keine In-App-Käufe",
        "def_title": "Was diese App ist",
        "def_body": "Fuse Beads: Pattern Maker ist eine iPhone-App von Shanghai Qishan Cultural Communication Co., Ltd. Der chinesische Name ist 拼豆时光. Apple-ID 6799906107. Bundle-ID com.weizhichao.beadday. Sie macht aus einem Foto aus Fotos, Kamera oder Dateien eine Vorlage für eine echte Steckplatte und enthält 24 eigene Vorlagen. Erzeugung, Bearbeitung, Stückzahlen, Nachlegen und Sicherungen bleiben auf dem Gerät. Die App erhebt keine Daten, spricht keinen Entwickler-Server an und enthält weder Werbung noch Analyse-SDK.",
        "story_title": "Eine Vorlage zum Bügeln",
        "story_body": "Du wählst Plattenmaß, Farbgrenze und eine Perler-, Hama- oder Artkal-Referenzpalette. Der Abgleich läuft auf dem Gerät mit wahrgenommenem Farbabstand und Kantenschutz. Danach änderst du Perle für Perle, prüfst Stückzahlen und markierst den Fortschritt nach Farbe.",
        "story_alt": "Corgi-Bügelperlenplatte, Pinzette, Schälchen und Sortierschale auf Leinen",
        "loop_title": "Vom Bild zur Platte",
        "loop1_title": "Foto oder Vorlage",
        "loop1_body": "Nutze die Systemauswahl, die Kamera oder Dateien, oder starte mit 24 eigenen Vorlagen. Der quadratische Zuschnitt kennt Zoom und Versatz. Die smarte Hintergrundentfernung bleibt aus, bis du sie einschaltest. Apple Vision schützt dann das Motiv auf dem Gerät.",
        "loop2_title": "Ändern, bis es steckbar ist",
        "loop2_body": "Farbe tippen, leere Zellen löschen, bis zu 30 Schritte zurück, zoomen, zu Zeile und Spalte springen. Die Materialliste zeigt Stückzahlen, Haken für vorhandene Farben, Packungsabschätzung und eine kopierbare Einkaufsliste.",
        "loop2_alt": "Katzenvorlage, Perle für Perle bearbeitet",
        "loop3_title": "Farbe für Farbe, dann exportieren",
        "loop3_body": "Eine Farbe hervorheben, gesetzte Perlen abhaken, Gesamtfortschritt und nächste Farbe sehen. PNG oder PDF mit Koordinaten exportieren. Große Platten teilen sich in 20×20-Abschnitte. Ein Fertigfoto kann im lokalen Projekt bleiben.",
        "loop3_alt": "Gänseblümchen-Vorlage zum Nachlegen",
        "spec_title": "Maße echter Platten",
        "spec_body": "Der übliche Start ist 40×40 mit 16 Farben. Kleine Motive passen auf 15×15 oder 21×21. Rechtecke und eigene Maße halten den Zuschnitt an der Platte.",
        "spec_boards": "Platten",
        "spec_boards_val": "15, 21, 29, 40, 58, plus eigene Maße",
        "spec_colors": "Farbgrenze",
        "spec_colors_val": "8, 12, 16 oder 24 Farben",
        "spec_library": "Eingebaute Vorlagen",
        "spec_library_val": "24 eigene Entwürfe",
        "spec_locales": "Sprachen",
        "spec_locales_val": "13 Sprachen, inklusive Arabisch RTL",
        "spec_export": "Export",
        "spec_export_val": "PNG und PDF mit Koordinaten",
        "pal_title": "Farbcodes sind Bildschirmreferenzen",
        "pal_body": "Perler-Namen, Hama-Midi-Nummern und Artkal-S-5mm-Nummern helfen bei einer ungefähren Palette. Die Marken gehören ihren Inhabern. Diese App ist nicht verbunden, gesponsert oder offiziell autorisiert. Prüfe vor größeren Einkäufen die aktuelle physische Farbkarte.",
        "pal_perler": "Perler-Namen",
        "pal_hama": "Hama-Midi-Nummern",
        "pal_artkal": "Artkal-S-5mm-Nummern",
        "locale_title": "Die Oberfläche folgt dir",
        "locale_body": "Oberfläche, Rechtehinweise und Rechtstexte folgen der Systemsprache oder einer Sprache in den Einstellungen. Arabisch läuft von rechts nach links. Diese Website hat pro Sprache eine eigene Adresse, damit Suche und Zitate die richtige Seite treffen.",
        "off_title": "Es bleibt auf diesem iPhone",
        "off1_title": "Nichts erhoben",
        "off1_body": "Keine Konten, keine Werbung, kein Analyse-SDK, kein Tracking. Fotos und Projekte gehen nicht auf einen Entwickler-Server.",
        "off2_title": "Arbeit auf dem Gerät",
        "off2_body": "Quantisierung, Hintergrund, Vorschauen und Sicherungen liegen im App-Container. Deinstallieren löscht lokale Vorlagen. Exportiere zuerst eine Sicherung in den Einstellungen.",
        "off3_title": "Du entscheidest, was geht",
        "off3_body": "Dateien verlassen die App nur, wenn du ein PNG in Fotos sicherst oder im Teilen-Menü ein Ziel wählst.",
        "cta_title": "Die erste Platte am Tisch",
        "cta_body": "Jetzt kostenlos im App Store. Keine Anmeldung. Öffne die App und mach aus einem Foto eine steckbare Vorlage.",
    },
    "support": {
        "title": "Hilfe · Fuse Beads",
        "description": "Hilfe zu Fuse Beads im App Store: Fotoimport, Erzeugung, Material, Nachlegen, Sicherung, Export und E-Mail-Kontakt. Die App läuft offline und erhebt keine Daten.",
        "lead": "Beginne mit Fragen aus dem echten Ablauf. Wenn du weiter Hilfe brauchst, schreib uns und füge den Diagnosetext aus der App ein.",
        "contact_title": "Support kontaktieren",
        "contact_body": "Es gibt kein Ticketsystem und keine Antwortfrist. Diese Seite und das Postfach sind dieselbe Tür.",
        "contact_mail": "Support-E-Mail",
        "contact_include": "Bitte angeben",
        "contact1": "App-Version aus den Einstellungen",
        "contact2": "iPhone-Modell und iOS-Version",
        "contact3": "Schritte zur Reproduktion",
        "contact4": "In den Einstellungen kopierter Diagnosetext",
        "contact_note": "Hänge keine Originalfotos mit privatem Inhalt an. Die Diagnose enthält weder Fotos noch Vorlagen.",
        "guides_title": "So entsteht eine Platte",
        "g1_title": "Foto zur Vorlage machen",
        "g1_body": "Starte auf der Startseite ein Foto-Projekt und wähle ein Bild aus Fotos, Kamera oder Dateien. Stelle Zuschnitt, Plattenmaß, Farbgrenze, Detailmodus und Referenzpalette ein. Ein sorgfältiger Start ist 40×40 mit 16 Farben. Lass die smarte Hintergrundentfernung aus, außer das Motiv ist klar und der Hintergrund stört. Sieh die Live-Vorschau, erzeuge, vergleiche mit dem Original oder gehe zurück.",
        "g2_title": "Material zählen und kaufen",
        "g2_body": "Unter Material siehst du Stückzahlen je Farbe. Hake vorhandene Farben ab, schätze Packungen und kopiere die Einkaufsliste. Bildschirmcodes sind Näherungen. Prüfe vor einem großen Einkauf die aktuelle physische Karte der Marke.",
        "g3_title": "Farbe für Farbe nachlegen",
        "g3_body": "Im Nachlegen wählst du eine Farbe, dann leuchtet nur sie. Tippe gesetzte Perlen, sieh den Gesamtstand und die nächste Farbe. Bei Bedarf bleibt der Bildschirm wach. Der Fortschritt liegt im lokalen Projekt.",
        "g4_title": "Export und Sicherung",
        "g4_body": "Exportiere PNG oder PDF mit Koordinaten aus dem Arbeitsbereich oder dem Projektmenü. Große Platten wie 58×58 erhalten 20×20-Abschnitte. Vor Gerätewechsel oder Löschen exportiere unter Ich → Einstellungen und Datenschutz eine JSON-Sicherung. Deinstallieren löscht alle Vorlagen in der Sandbox.",
        "faq_title": "Häufige Fragen",
        "download_title": "Wo herunterladen",
        "download_body": "Fuse Beads: Pattern Maker ist im App Store für iPhone, iOS 17 oder neuer. Kostenlos, ohne In-App-Käufe oder Abos. Verkauf in 175 Ländern oder Regionen.",
        "faqs": [
            ("Werden meine Fotos hochgeladen?", "Nein. Fotos aus der Systemauswahl, der Kamera oder Dateien werden nur auf dem Gerät verarbeitet. Die smarte Hintergrundentfernung nutzt Apple Vision auf dem Gerät. Fotos und Masken gehen nicht auf einen Server."),
            ("Warum sieht die Vorlage falsch aus?", "Scharfe Vorlage, Zuschnitt, Maß, Farbgrenze und Detailmodus entscheiden. Der übliche Qualitätsweg ist 40×40 mit 16 Farben. Nutze die Live-Vorschau, vergleiche mit dem Original oder gehe zurück. Nach dem Speichern kannst du vom Original neu erzeugen."),
            ("Wie funktioniert die smarte Hintergrundentfernung?", "Sie ist standardmäßig aus. Eingeschaltet schützt sie das Motiv auf dem Gerät und behandelt verbundenen Hintergrund als leere Zellen. Verschwinden Kanten oder bleibt Hintergrund, schalte sie aus und editiere per Hand, oder nimm ein klareres Motivfoto."),
            ("Kann ich nach Bildschirmcodes kaufen?", "Siehe sie als ungefähre Referenz, nicht als Werksfarbe. Displays und Chargen weichen ab. Vergleiche vor großen Einkäufen die aktuelle physische Karte."),
            ("Wohin gehen PNG und PDF?", "Export aus Arbeitsbereich oder Projektmenü. PNG kann mit Nur-hinzufügen-Recht in Fotos. Die App liest die Mediathek damit nicht. PDFs haben Koordinaten. Große Platten wie 58×58 bekommen 20×20-Seiten. Anderes Teilen läuft über das Systemmenü."),
            ("Ein Projekt fehlt oder öffnet nicht.", "Daten liegen in Application Support/BeadTime. Beschädigte Einträge werden als projects-invalid isoliert, der Rest öffnet. Exportiere zuerst eine Sicherung. Ist die Bibliothek zu groß, wird das Original beiseitegelegt und nicht überschrieben."),
            ("Wie werden Sicherungen zusammengeführt?", "Einstellungen exportieren eine versionierte JSON-Sicherung und importieren mit Merge. Beim gleichen Projekt gewinnt die neuere Änderungszeit. Sicherungen einer neueren App-Version gehen nicht. Zu große Dateien oder zu viele Projekte werden abgelehnt."),
            ("Bleiben Vorlagen nach dem Löschen?", "Nein. Deinstallieren löscht Sandbox-Vorlagen, Vorschauen und Fortschritt. Exportiere vorher eine lokale Sicherung."),
            ("Wie kopiere ich die Diagnose?", "Ich → Einstellungen und Datenschutz → Diagnoseinformationen kopieren. Enthalten sind App-Version, Gerät, System und lokale Projektzahl, keine Fotos oder Vorlagen. Füge den Text in die Support-Mail ein."),
            ("Welche Sprachen gibt es?", "Englisch, vereinfachtes Chinesisch, traditionelles Chinesisch, Japanisch, Koreanisch, Spanisch, Französisch, Deutsch, brasilianisches Portugiesisch, Italienisch, Russisch, Arabisch (rechts nach links) und Hindi. Folge dem System oder lege eine Sprache in den Einstellungen fest."),
            ("Wozu die Kameraerlaubnis?", "Nur wenn du ein Foto für eine Vorlage aufnimmst. Auch das bleibt auf dem Gerät. Standort, Mikrofon, Kontakte und Tracking werden nicht genutzt."),
            ("Geht es ohne Netz?", "Ja. Das Herstellen läuft vollständig offline. Netz brauchst du nur für diese Seite oder E-Mail. Die App spricht keinen Entwickler-Server an."),
            ("Ist die App kostenlos?", "Ja. Fuse Beads ist im App Store kostenlos. Es gibt keine In-App-Käufe, Abos oder Konten. Öffnen und loslegen."),
            ("Läuft sie auf iPad oder Mac?", "Die App ist für iPhone mit iOS 17 oder neuer. iPad, Mac und Apple Vision Pro sind keine Store-Ziele. Lade sie auf dem iPhone."),
            ("Wer steckt dahinter?", "Shanghai Qishan Cultural Communication Co., Ltd. Support: 281916057@qq.com."),
        ],
    },
    "privacy": {
        "title": "Datenschutz · Fuse Beads",
        "description": "Fuse Beads erhebt keine Daten. Fotos, Vorlagen und Fortschritt bleiben auf dem iPhone. Kein Konto, keine Werbung, keine Analyse, keine Cloud-Sync.",
        "lead": "Diese Erklärung beschreibt, was Fuse Beads mit Daten wirklich tut. Die App ist im App Store. Sie erhebt keine Daten und sendet deine Inhalte nicht an einen Entwickler-Server.",
        "updated": "Zuletzt aktualisiert: 18. September 2026. Die Praxis entspricht dem öffentlichen Text vom 17. September 2026. Diese Fassung hält fest, dass die App live ist, die Erklärung als crawlbare Seiten steht und die Website keine Cookies nutzt.",
        "toc_label": "Auf dieser Seite",
        "toc": [
            ("#collect", "Was wir erheben"),
            ("#photos", "Fotos und Kamera"),
            ("#storage", "Lokaler Speicher"),
            ("#share", "Fotos und Teilen"),
            ("#controls", "Deine Kontrolle"),
            ("#children", "Kinder"),
            ("#third", "Dritte"),
            ("#contact", "Updates und Kontakt"),
        ],
        "sections": [
            ("collect", "Was wir erheben", "Nichts. Der Entwickler erhebt aus der App keine Fotos, Vorlagen, Materiallisten, Fortschritte oder Nutzungsdaten. Es gibt kein Konto, keine Werbung, kein Analyse-SDK, keinen Absturzmelder, keine Cloud-Sync und kein Tracking über Apps hinweg. Das App-Store-Datenschutzlabel sagt: Wir erheben keine Daten aus dieser App. Das Privacy Manifest listet keine Datentypen. UserDefaults speichert nur den Abschluss der Einführung und die Sprachwahl."),
            ("photos", "Fotos und Kamera", "Fotos aus Mediathek oder Dateien oder Aufnahmen mit der Systemkamera dienen nur auf dem Gerät dem Erzeugen von Vorlagen. Ist die smarte Hintergrundentfernung an, findet Apple Vision das Motiv auf dem Gerät. Fotos und Masken gehen nicht an Apple, den Entwickler oder einen Server. Die App legt eine eigene komprimierte Vorschau im Container für Bearbeitung und Sicherung ab."),
            ("storage", "Lokaler Speicher und Aufbewahrung", "Metadaten, Zellen, Materialhaken, Nachlegefortschritt und komprimierte Vorschauen bleiben in Application Support/BeadTime in der Sandbox, bis du ein Projekt löschst, alle Projekte in den Einstellungen löschst oder die App entfernst. Sicherung, PNG oder PDF kannst du jederzeit exportieren. Ungültige Daten werden isoliert und überschreiben andere Projekte nicht."),
            ("share", "Speichern in Fotos und Teilen", "Bei „PNG in Fotos sichern“ fragt die App nur das Hinzufügen an und schreibt den gewählten Export. Sie liest die Mediathek damit nicht. Andere Exporte verlassen das Gerät nur über das Teilen-Menü und das Ziel, das du wählst. Systemauswahl und Teilen-Ziel sind keine Erhebung durch den Entwickler."),
            ("controls", "Deine Kontrolle", "Du kannst nur gewählte Fotos geben, Projekte oder alle lokalen Daten löschen und Sicherungen exportieren. Diese Website ist statisch und nur lesbar. Sie verlangt keine Anmeldung und nutzt keine Formulare, Cookies, Analysen, Werbung oder Datenbank. Die Sprache steckt in der Adresse. Das Support-Postfach erhält nur, was du sendest."),
            ("children", "Kinder und sensible Daten", "Die App legt keine Kinderkonten an und fragt nicht nach Namen, Kontaktdaten oder anderen sensiblen Angaben. Die Altersfreigabe ist 4+, Familien dürfen sie gemeinsam nutzen. Importiere kein Foto, dessen Inhalt du nicht lokal speichern willst. Die App ist nicht darauf ausgelegt, personenbezogene Daten von Kindern zu erheben."),
            ("third", "Dritte und Server", "Die App hat kein Laufzeit-SDK Dritter und spricht kein Entwickler-Backend an. Die Hintergrundentfernung nutzt das Vision-Framework von iOS auf dem Gerät. Diese Website enthält bei dokumentiertem Hosting keine Analyse- oder Werbeskripte. E-Mail läuft über den Anbieter, den du zum Schreiben nutzt."),
            ("contact", "Updates und Kontakt", "Ändert sich die Praxis wesentlich, aktualisieren wir diese Erklärung und das Datum. Entwickler: Shanghai Qishan Cultural Communication Co., Ltd. Fragen an 281916057@qq.com."),
        ],
    },
}

FR = {
    "chrome": {
        "brand_zh": "拼豆时光",
        "brand_en": "Fuse Beads",
        "nav_home": "Accueil",
        "nav_support": "Assistance",
        "nav_privacy": "Confidentialité",
        "nav_open": "Ouvrir le menu",
        "nav_close": "Fermer le menu",
        "nav_aria": "Navigation principale",
        "skip": "Aller au contenu",
        "lang_aria": "Langue",
        "cta_store": "Télécharger sur l’App Store",
        "footer_explore": "Explorer",
        "footer_help": "Aide",
        "footer_legal": "Mentions",
        "footer_copy": "2026 Shanghai Qishan Cultural Communication Co., Ltd. 拼豆时光 / Fuse Beads. Les couleurs à l’écran sont approximatives. Perler, Hama et Artkal sont des marques de leurs titulaires.",
        "lost_title": "Pas de perles sur cette page",
        "lost_body": "Cette adresse n’est pas dans la boîte. Retour à l’accueil, à l’assistance ou à la politique de confidentialité.",
        "lost_home": "Retour à l’accueil",
    },
    "home": {
        "title": "Fuse Beads : appli hors ligne de perles à repasser sur l’App Store",
        "description": "Fuse Beads: Pattern Maker est sur l’App Store. Une photo devient un motif à poser sur iPhone. Modifier perle par perle, compter les matériaux, suivre couleur par couleur, exporter PNG ou PDF. Gratuit. Sans compte. Sans collecte de données.",
        "live": "Sur l’App Store",
        "hero_title": "Poser l’idée sur la plaque",
        "hero_lede": "Fuse Beads est une appli iPhone entièrement hors ligne pour les motifs de perles à repasser. Choisissez une photo ou un motif intégré, créez un schéma modifiable sur cet appareil, préparez les perles et avancez couleur par couleur.",
        "cta_how": "Voir le parcours",
        "meta1": "Sans compte",
        "meta2": "iOS 17 ou plus récent",
        "meta3": "Gratuit, sans achats intégrés",
        "def_title": "Ce qu’est cette appli",
        "def_body": "Fuse Beads: Pattern Maker est une appli iPhone de Shanghai Qishan Cultural Communication Co., Ltd. Le nom chinois est 拼豆时光. Identifiant Apple 6799906107. Bundle ID com.weizhichao.beadday. Elle transforme une photo de Photos, de l’appareil ou de Fichiers en motif réalisable sur une vraie plaque, avec 24 motifs originaux intégrés. Génération, édition, quantités, suivi et sauvegardes restent sur l’appareil. L’appli ne collecte pas de données, n’appelle aucun serveur développeur et n’embarque ni publicité ni SDK d’analyse.",
        "story_title": "Un motif que l’on peut repasser",
        "story_body": "Vous choisissez la taille de plaque, la limite de couleurs et une palette Perler, Hama ou Artkal. L’appariement se fait sur l’appareil avec une différence de couleur perceptuelle et un soin des bords. Ensuite vous corrigez perle par perle, vérifiez les quantités et cochez la progression par couleur.",
        "story_alt": "Plaque corgi, pince, bol et plateau trié sur du lin",
        "loop_title": "D’une image à une plaque",
        "loop1_title": "Photo ou motif intégré",
        "loop1_body": "Utilisez le sélecteur système, l’appareil photo ou Fichiers, ou partez de 24 motifs originaux. Le cadrage carré permet zoom et décalage. Le nettoyage intelligent du fond reste éteint jusqu’à ce que vous l’activiez. Apple Vision protège alors le sujet sur l’appareil.",
        "loop2_title": "Corriger jusqu’à pouvoir poser",
        "loop2_body": "Touchez pour recolorer, effacez les cases vides, annulez jusqu’à 30 pas, zoomez, sautez à une ligne ou une colonne. La liste matériaux montre les quantités, les couleurs déjà prêtes, l’estimation des sachets et une liste d’achats copiable.",
        "loop2_alt": "Motif de chat corrigé perle par perle",
        "loop3_title": "Suivre par couleur, puis exporter",
        "loop3_body": "Mettez une couleur en avant, cochez les perles posées, voyez la progression et la suivante. Exportez un PNG ou un PDF avec coordonnées. Les grandes plaques se découpent en pages 20×20. Une photo du résultat peut rester dans le projet local.",
        "loop3_alt": "Motif de pâquerette pour le suivi",
        "spec_title": "Des tailles de vraies plaques",
        "spec_body": "Le départ habituel est 40×40 et 16 couleurs. Les petits motifs vont en 15×15 ou 21×21. Rectangles et formats perso gardent le cadrage aligné sur la plaque.",
        "spec_boards": "Plaques",
        "spec_boards_val": "15, 21, 29, 40, 58, plus formats perso",
        "spec_colors": "Limite de couleurs",
        "spec_colors_val": "8, 12, 16 ou 24 couleurs",
        "spec_library": "Motifs intégrés",
        "spec_library_val": "24 créations originales",
        "spec_locales": "Langues",
        "spec_locales_val": "13 langues, arabe RTL compris",
        "spec_export": "Export",
        "spec_export_val": "PNG et PDF avec coordonnées",
        "pal_title": "Les codes couleur sont des références écran",
        "pal_body": "Noms Perler, numéros Hama Midi et Artkal S-5mm aident à choisir une palette approchante. Ces marques appartiennent à leurs titulaires. Cette appli n’est ni affiliée, ni sponsorisée, ni officiellement autorisée. Vérifiez la carte physique à jour avant un gros achat.",
        "pal_perler": "Noms Perler",
        "pal_hama": "Numéros Hama Midi",
        "pal_artkal": "Numéros Artkal S-5mm",
        "locale_title": "L’interface vous suit",
        "locale_body": "Interface, textes d’autorisation et mentions suivent la langue du système, ou une langue verrouillée dans Réglages. L’arabe va de droite à gauche. Ce site a une adresse distincte par langue, pour la recherche et les citations.",
        "off_title": "Cela reste sur cet iPhone",
        "off1_title": "Rien n’est collecté",
        "off1_body": "Pas de compte, de publicité, de SDK d’analyse ni de suivi. L’appli n’envoie pas photos ni projets vers un serveur développeur.",
        "off2_title": "Travail sur l’appareil",
        "off2_body": "Quantification, fond, aperçus et sauvegardes vivent dans le conteneur de l’appli. Désinstaller efface les motifs locaux : exportez d’abord une sauvegarde dans Réglages.",
        "off3_title": "Vous choisissez ce qui sort",
        "off3_body": "Les fichiers quittent l’appli seulement si vous enregistrez un PNG dans Photos ou choisissez une destination dans la feuille de partage.",
        "cta_title": "La première plaque sur la table",
        "cta_body": "Gratuit sur l’App Store maintenant. Sans inscription. Ouvrez l’appli et transformez une photo en motif à poser.",
    },
    "support": {
        "title": "Assistance · Fuse Beads",
        "description": "Aide Fuse Beads sur l’App Store : import photo, génération, matériaux, suivi, sauvegarde, export et contact. L’appli est hors ligne et ne collecte pas de données.",
        "lead": "Partez des questions du vrai parcours. S’il faut encore de l’aide, écrivez et collez le texte de diagnostic de l’appli.",
        "contact_title": "Contacter l’assistance",
        "contact_body": "Pas de système de tickets ni de délai promis. Cette page et la boîte mail sont la même porte.",
        "contact_mail": "E-mail d’assistance",
        "contact_include": "Merci d’indiquer",
        "contact1": "Version de l’appli dans Réglages",
        "contact2": "Modèle d’iPhone et version d’iOS",
        "contact3": "Étapes pour reproduire",
        "contact4": "Texte de diagnostic copié dans Réglages",
        "contact_note": "N’attachez pas de photos originales au contenu privé. Le diagnostic omet photos et motifs.",
        "guides_title": "Comment poser une plaque",
        "g1_title": "Transformer une photo en motif",
        "g1_body": "Sur l’accueil, lancez un projet photo et choisissez une image dans Photos, l’appareil ou Fichiers. Réglez cadrage, taille, limite de couleurs, mode de détail et palette. Un départ soigné est 40×40 et 16 couleurs. Laissez le nettoyage du fond éteint sauf si le sujet est net et le fond gênant. Regardez l’aperçu, générez, comparez à l’original ou revenez ajuster.",
        "g2_title": "Compter et acheter",
        "g2_body": "Dans Matériaux, voyez les quantités par couleur. Cochez celles déjà chez vous, estimez les sachets et copiez la liste. Les codes écran sont approximatifs. Vérifiez la carte physique actuelle de la marque avant un gros achat.",
        "g3_title": "Suivre couleur par couleur",
        "g3_body": "Dans Suivi, choisissez une couleur : elle seule est mise en avant. Touchez les perles posées, voyez l’avancement et la suivante. Gardez l’écran allumé si besoin. La progression reste dans le projet local.",
        "g4_title": "Exporter et sauvegarder",
        "g4_body": "Exportez PNG ou PDF avec coordonnées depuis l’espace de travail ou le menu du projet. Les grandes plaques comme 58×58 ont des pages 20×20. Avant de changer de téléphone ou de supprimer l’appli, exportez une sauvegarde JSON depuis Moi → Réglages et confidentialité. Désinstaller efface tous les motifs du bac à sable.",
        "faq_title": "Questions fréquentes",
        "download_title": "Où télécharger",
        "download_body": "Fuse Beads: Pattern Maker est sur l’App Store pour iPhone, iOS 17 ou plus récent. Gratuit, sans achats intégrés ni abonnement. Vendu dans 175 pays ou régions.",
        "faqs": [
            ("Mes photos sont-elles envoyées ?", "Non. Les photos du sélecteur, de l’appareil ou de Fichiers sont traitées seulement sur l’appareil. Le nettoyage du fond utilise Apple Vision sur l’appareil. Photos et masques ne partent pas vers un serveur."),
            ("Pourquoi le motif paraît faux ?", "La netteté, le cadrage, la taille, la limite de couleurs et le mode de détail comptent. Le chemin habituel est 40×40 et 16 couleurs. Utilisez l’aperçu, confirmez face à l’original ou revenez. Après enregistrement, vous pouvez régénérer depuis l’original."),
            ("Comment marche le nettoyage du fond ?", "Il est éteint par défaut. Activé, il protège le sujet sur l’appareil et traite le fond connecté comme des cases vides. Si les bords disparaissent ou que le fond reste, éteignez-le et corrigez à la main, ou prenez une photo plus nette."),
            ("Puis-je acheter avec les codes écran ?", "Ce sont des références approximatives, pas des teintes d’usine. Écrans et lots varient. Comparez la carte physique actuelle avant un gros achat."),
            ("Où vont PNG et PDF ?", "Export depuis l’espace de travail ou le menu du projet. Le PNG peut aller dans Photos avec un accès ajout seulement ; l’appli ne lit pas la photothèque avec cet accès. Les PDF ont des coordonnées. Les grandes plaques comme 58×58 ajoutent des pages 20×20. Le reste passe par la feuille de partage."),
            ("Un projet manque ou ne s’ouvre pas.", "Les données sont dans Application Support/BeadTime. Les éléments abîmés sont isolés en projects-invalid, le reste s’ouvre. Exportez d’abord une sauvegarde. Si le fichier bibliothèque est trop grand, l’original est mis de côté et n’est pas écrasé."),
            ("Comment fusionner une sauvegarde ?", "Réglages exporte une sauvegarde JSON versionnée et l’importe en fusion. Pour un même projet, la date de mise à jour la plus récente l’emporte. Une sauvegarde d’une appli plus récente ne s’importe pas. Fichiers trop lourds ou trop de projets sont refusés."),
            ("La désinstallation garde-t-elle les motifs ?", "Non. Elle efface motifs, aperçus et progression du bac à sable. Exportez une sauvegarde locale avant de supprimer l’appli ou de changer de téléphone."),
            ("Comment copier le diagnostic ?", "Moi → Réglages et confidentialité → Copier les informations de diagnostic. Version, appareil, système et nombre de projets locaux, sans photos ni motifs. Collez-le dans le mail d’assistance."),
            ("Quelles langues ?", "Anglais, chinois simplifié, chinois traditionnel, japonais, coréen, espagnol, français, allemand, portugais brésilien, italien, russe, arabe (droite à gauche) et hindi. Suivez le système ou verrouillez une langue dans Réglages."),
            ("Pourquoi l’appareil photo ?", "Seulement si vous choisissez de photographier un motif. Cette photo est aussi traitée sur l’appareil. Pas de localisation, micro, contacts ni suivi."),
            ("Ça marche sans réseau ?", "Oui. La création est hors ligne. Le réseau sert à ouvrir ce site ou envoyer un mail. L’appli n’appelle pas de serveur développeur."),
            ("L’appli est-elle gratuite ?", "Oui. Gratuite sur l’App Store, sans achats intégrés, abonnement ni compte. Ouvrez et commencez."),
            ("Sur iPad ou Mac ?", "Conçue pour iPhone sous iOS 17 ou plus récent. iPad, Mac et Apple Vision Pro ne sont pas des destinations App Store. Téléchargez-la sur iPhone."),
            ("Qui édite Fuse Beads ?", "Shanghai Qishan Cultural Communication Co., Ltd. Assistance : 281916057@qq.com."),
        ],
    },
    "privacy": {
        "title": "Politique de confidentialité · Fuse Beads",
        "description": "Fuse Beads ne collecte pas de données. Photos, motifs et progression restent sur l’iPhone. Pas de compte, publicité, analyse ni sync cloud.",
        "lead": "Cette politique décrit ce que Fuse Beads fait réellement des données. L’appli est sur l’App Store. Elle ne collecte pas de données et n’envoie pas vos contenus à un serveur développeur.",
        "updated": "Dernière mise à jour : 18 septembre 2026. Les pratiques correspondent au texte public du 17 septembre 2026. Cette édition précise que l’appli est en ligne, publie la politique en pages indexables et indique que le site n’utilise pas de cookies.",
        "toc_label": "Sur cette page",
        "toc": [
            ("#collect", "Ce que nous collectons"),
            ("#photos", "Photos et appareil"),
            ("#storage", "Stockage local"),
            ("#share", "Photos et partage"),
            ("#controls", "Vos contrôles"),
            ("#children", "Enfants"),
            ("#third", "Tiers"),
            ("#contact", "Mises à jour et contact"),
        ],
        "sections": [
            ("collect", "Ce que nous collectons", "Rien. Le développeur ne collecte ni photos, ni motifs, ni listes de matériaux, ni progression, ni journaux d’usage. Pas de compte, publicité, SDK d’analyse, rapport de plantage, sync cloud ni suivi inter-applis. L’étiquette App Store dit que nous ne collectons pas de données de cette appli. Le manifeste de confidentialité n’liste aucun type collecté. UserDefaults ne stocke que la fin de l’accueil et la langue."),
            ("photos", "Photos et appareil", "Les photos choisies dans la photothèque ou Fichiers, ou prises avec l’appareil système, servent seulement sur l’appareil à créer des motifs. Si le nettoyage du fond est actif, Apple Vision trouve et protège le sujet sur l’appareil. Photos et masques ne partent ni vers Apple, ni vers le développeur, ni vers un serveur. L’appli garde un aperçu compressé distinct dans son conteneur pour l’édition et les sauvegardes."),
            ("storage", "Stockage local et conservation", "Métadonnées, perles, coches matériaux, progression et aperçus compressés restent dans Application Support/BeadTime du bac à sable jusqu’à suppression d’un projet, de tous les projets ou de l’appli. Vous pouvez exporter sauvegarde, PNG ou PDF à tout moment. Les données invalides sont isolées et n’écrasent pas les autres projets."),
            ("share", "Enregistrement dans Photos et partage", "En enregistrant un PNG dans Photos, l’appli demande un accès ajout seulement et écrit l’export choisi. Elle ne lit pas la photothèque avec cet accès. Les autres exports quittent l’appareil seulement via la feuille de partage et la destination choisie. Le sélecteur système et cette destination ne sont pas une collecte développeur."),
            ("controls", "Vos contrôles", "Vous pouvez ne fournir que les photos choisies, supprimer des projets ou toutes les données locales, et exporter des sauvegardes. Ce site est statique en lecture seule. Pas de connexion, formulaire, cookie, analyse, publicité ni base. La langue vient de l’adresse. La boîte d’assistance ne reçoit que ce que vous envoyez."),
            ("children", "Enfants et informations sensibles", "L’appli ne crée pas de comptes enfants et ne demande ni nom, ni coordonnées, ni autres données sensibles. L’âge suggéré est 4+, les familles peuvent l’utiliser ensemble. N’importez pas une photo dont le contenu ne doit pas rester dans un projet local. L’appli n’est pas conçue pour collecter des données d’enfants."),
            ("third", "Tiers et serveurs", "Aucun SDK tiers au runtime, aucun backend développeur. Le nettoyage du fond utilise Vision, fourni avec iOS, sur l’appareil. Hébergé comme documenté, ce site n’a ni script d’analyse ni publicité. Le courrier passe par le fournisseur que vous utilisez pour écrire."),
            ("contact", "Mises à jour et contact", "Si les pratiques changent de façon substantielle, nous mettrons à jour cette politique et sa date. Éditeur : Shanghai Qishan Cultural Communication Co., Ltd. Questions : 281916057@qq.com."),
        ],
    },
}

ES = {
    "chrome": {
        "brand_zh": "拼豆时光",
        "brand_en": "Fuse Beads",
        "nav_home": "Inicio",
        "nav_support": "Ayuda",
        "nav_privacy": "Privacidad",
        "nav_open": "Abrir menú",
        "nav_close": "Cerrar menú",
        "nav_aria": "Navegación principal",
        "skip": "Ir al contenido",
        "lang_aria": "Idioma",
        "cta_store": "Descargar en el App Store",
        "footer_explore": "Explorar",
        "footer_help": "Ayuda",
        "footer_legal": "Legal",
        "footer_copy": "2026 Shanghai Qishan Cultural Communication Co., Ltd. 拼豆时光 / Fuse Beads. Los colores de pantalla son aproximados. Perler, Hama y Artkal son marcas de sus titulares.",
        "lost_title": "No hay cuentas en esta página",
        "lost_body": "Esa dirección no está en la caja. Vuelve al sitio, a la ayuda o a la política de privacidad.",
        "lost_home": "Volver al inicio",
    },
    "home": {
        "title": "Fuse Beads: app offline de cuentas para planchar en el App Store",
        "description": "Fuse Beads: Pattern Maker está en el App Store. Convierte una foto en un patrón que puedes planchar en el iPhone. Edita cuenta a cuenta, cuenta materiales, sigue color a color, exporta PNG o PDF. Gratis. Sin cuenta. Sin recopilar datos.",
        "live": "En el App Store",
        "hero_title": "Pon la idea en el tablero",
        "hero_lede": "Fuse Beads es una app de iPhone totalmente sin conexión para patrones de cuentas para planchar. Elige una foto o un diseño incluido, genera un patrón editable en este teléfono, prepara cuentas y termina color a color.",
        "cta_how": "Ver el proceso",
        "meta1": "Sin cuenta",
        "meta2": "iOS 17 o posterior",
        "meta3": "Gratis, sin compras dentro de la app",
        "def_title": "Qué es esta app",
        "def_body": "Fuse Beads: Pattern Maker es una app de iPhone de Shanghai Qishan Cultural Communication Co., Ltd. El nombre chino es 拼豆时光. Apple ID 6799906107. Bundle ID com.weizhichao.beadday. Convierte una foto de Fotos, la cámara o Archivos en un patrón para un tablero real, e incluye 24 diseños originales. Generación, edición, materiales, seguimiento y copias se quedan en el dispositivo. No recopila datos, no habla con un servidor del desarrollador y no lleva anuncios ni SDK de analítica.",
        "story_title": "Un patrón que se puede planchar",
        "story_body": "Eliges tamaño, límite de color y una paleta Perler, Hama o Artkal. El ajuste ocurre en el dispositivo con diferencia de color perceptiva y cuidado del borde. Luego editas cuenta a cuenta, revisas cantidades y marcas el avance por color.",
        "story_alt": "Tablero de corgi, pinzas, cuenco y bandeja clasificada sobre lino",
        "loop_title": "De una imagen a un tablero",
        "loop1_title": "Foto o diseño incluido",
        "loop1_body": "Usa el selector del sistema, la cámara o Archivos, o empieza con 24 diseños originales. El recorte cuadrado admite zoom y desplazamiento. La limpieza inteligente del fondo permanece apagada hasta que la actives. Apple Vision protege entonces el motivo en el dispositivo.",
        "loop2_title": "Editar hasta que se pueda hacer",
        "loop2_body": "Toca para recolorear, borra celdas vacías, deshaz hasta 30 pasos, amplía y salta a fila o columna. La lista de materiales cubre cantidades, marcas de listo, estimación de bolsas y una lista de compra copiable.",
        "loop2_alt": "Patrón de gato editado cuenta a cuenta",
        "loop3_title": "Seguir por color y exportar",
        "loop3_body": "Resalta un color, marca cuentas puestas y ve el avance y el siguiente. Exporta PNG o PDF con coordenadas. Los tableros grandes se parten en páginas 20×20. Una foto terminada puede quedarse en el proyecto local.",
        "loop3_alt": "Patrón de margarita para el seguimiento",
        "spec_title": "Tamaños de tableros reales",
        "spec_body": "El punto de partida habitual es 40×40 con 16 colores. Los amuletos pequeños caben en 15×15 o 21×21. Rectángulos y medidas propias mantienen el recorte alineado al tablero.",
        "spec_boards": "Tableros",
        "spec_boards_val": "15, 21, 29, 40, 58, más personalizado",
        "spec_colors": "Límite de color",
        "spec_colors_val": "8, 12, 16 o 24 colores",
        "spec_library": "Patrones incluidos",
        "spec_library_val": "24 diseños originales",
        "spec_locales": "Idiomas",
        "spec_locales_val": "13 idiomas, árabe RTL incluido",
        "spec_export": "Exportar",
        "spec_export_val": "PNG y PDF con coordenadas",
        "pal_title": "Los códigos son referencia en pantalla",
        "pal_body": "Nombres Perler, números Hama Midi y Artkal S-5mm ayudan a elegir una paleta aproximada. Esas marcas pertenecen a sus titulares. Esta app no está afiliada, patrocinada ni autorizada oficialmente. Comprueba la carta física actual antes de comprar en cantidad.",
        "pal_perler": "Nombres Perler",
        "pal_hama": "Números Hama Midi",
        "pal_artkal": "Números Artkal S-5mm",
        "locale_title": "La interfaz te sigue",
        "locale_body": "La interfaz, los textos de permiso y el texto legal siguen el idioma del sistema o uno fijado en Ajustes. El árabe va de derecha a izquierda. Este sitio usa una dirección distinta por idioma para que se pueda buscar y citar la página correcta.",
        "off_title": "Se queda en este iPhone",
        "off1_title": "Nada recopilado",
        "off1_body": "Sin cuentas, anuncios, SDK de analítica ni seguimiento. La app no sube fotos ni proyectos a un servidor del desarrollador.",
        "off2_title": "Trabajo en el dispositivo",
        "off2_body": "Cuantización, fondo, vistas previas y copias viven en el contenedor de la app. Desinstalar borra los patrones locales: exporta antes una copia en Ajustes.",
        "off3_title": "Tú eliges lo que sale",
        "off3_body": "Los archivos salen solo si guardas un PNG en Fotos o eliges un destino en la hoja de compartir.",
        "cta_title": "El primer tablero en la mesa",
        "cta_body": "Gratis ahora en el App Store. Sin registro. Abre la app y convierte una foto en un patrón que se puede montar.",
    },
    "support": {
        "title": "Ayuda · Fuse Beads",
        "description": "Ayuda de Fuse Beads en el App Store: importar fotos, generar, materiales, seguimiento, copias, exportar y escribir al soporte. La app es offline y no recopila datos.",
        "lead": "Empieza por preguntas del flujo real. Si aún necesitas ayuda, escribe y pega el texto de diagnóstico de la app.",
        "contact_title": "Contactar con soporte",
        "contact_body": "No hay sistema de tickets ni plazo de respuesta. Esta página y el buzón son la misma puerta.",
        "contact_mail": "Correo de soporte",
        "contact_include": "Incluye",
        "contact1": "Versión de la app en Ajustes",
        "contact2": "Modelo de iPhone y versión de iOS",
        "contact3": "Pasos para reproducir",
        "contact4": "Texto de diagnóstico copiado en Ajustes",
        "contact_note": "No adjuntos fotos originales con contenido privado. El diagnóstico omite fotos y patrones.",
        "guides_title": "Cómo hacer un tablero",
        "g1_title": "Convertir una foto en patrón",
        "g1_body": "En Inicio, empieza un proyecto de foto y elige una imagen de Fotos, la cámara o Archivos. Ajusta recorte, tamaño, límite de color, detalle y paleta. Un valor cuidadoso es 40×40 con 16 colores. Deja apagada la limpieza de fondo salvo que el motivo sea claro y el fondo estorbe. Mira la vista previa, genera, compara con el original o vuelve a ajustar.",
        "g2_title": "Contar materiales y comprar",
        "g2_body": "En Materiales ves cantidades por color. Marca los que ya tienes, estima bolsas y copia la lista. Los códigos de pantalla son aproximados. Revisa la carta física actual de la marca antes de una compra grande.",
        "g3_title": "Seguir color a color",
        "g3_body": "En Seguir, elige un color para resaltarlo solo. Toca las cuentas puestas, mira el avance y el siguiente. Mantén la pantalla encendida si lo necesitas. El progreso se queda en el proyecto local.",
        "g4_title": "Exportar y copiar",
        "g4_body": "Exporta PNG o PDF con coordenadas desde el espacio de trabajo o el menú del proyecto. Tableros grandes como 58×58 incluyen páginas 20×20. Antes de cambiar de teléfono o borrar la app, exporta una copia JSON en Yo → Ajustes y privacidad. Desinstalar borra todos los patrones del entorno aislado.",
        "faq_title": "Preguntas frecuentes",
        "download_title": "Dónde descargar",
        "download_body": "Fuse Beads: Pattern Maker está en el App Store para iPhone, iOS 17 o posterior. Gratis, sin compras dentro de la app ni suscripciones. Se vende en 175 países o regiones.",
        "faqs": [
            ("¿Se suben mis fotos?", "No. Las fotos del selector, la cámara o Archivos se procesan solo en el dispositivo. La limpieza de fondo usa Apple Vision en el dispositivo. Fotos y máscaras no van a un servidor."),
            ("¿Por qué el patrón se ve mal?", "Depende de la nitidez, el recorte, el tamaño, el límite de color y el detalle. El camino habitual es 40×40 con 16 colores. Usa la vista previa, confirma frente al original o vuelve. Tras guardar también puedes regenerar desde el original."),
            ("¿Cómo funciona la limpieza de fondo?", "Va apagada por defecto. Al activarla protege el motivo en el dispositivo y trata el fondo conectado como celdas vacías. Si se cortan bordes o queda fondo, apágala y edita a mano, o usa una foto más clara."),
            ("¿Puedo comprar con los códigos de pantalla?", "Son referencias aproximadas, no colores de fábrica. Pantallas y lotes varían. Compara la carta física actual antes de una compra grande."),
            ("¿Dónde van PNG y PDF?", "Exporta desde el espacio de trabajo o el menú del proyecto. El PNG puede guardarse en Fotos con acceso solo para añadir; la app no lee la biblioteca con ese permiso. Los PDF llevan coordenadas. Tableros grandes como 58×58 añaden páginas 20×20. El resto usa la hoja de compartir."),
            ("Falta un proyecto o no abre.", "Los datos están en Application Support/BeadTime. Los dañados se aíslan como projects-invalid y el resto abre. Exporta primero una copia. Si el archivo de biblioteca es demasiado grande, el original se aparta y no se sobrescribe."),
            ("¿Cómo se fusionan las copias?", "Ajustes exporta una copia JSON versionada e importa con fusión. En el mismo proyecto gana la fecha de actualización más reciente. Una copia de una app más nueva no se importa. Archivos demasiado grandes o demasiados proyectos se rechazan."),
            ("¿Desinstalar guarda los patrones?", "No. Borra patrones, vistas previas y progreso del entorno aislado. Exporta una copia local antes de quitar la app o cambiar de teléfono."),
            ("¿Cómo copio el diagnóstico?", "Yo → Ajustes y privacidad → Copiar información de diagnóstico. Incluye versión, dispositivo, sistema y número de proyectos locales, no fotos ni patrones. Pégalo en el correo de soporte."),
            ("¿Qué idiomas hay?", "Inglés, chino simplificado, chino tradicional, japonés, coreano, español, francés, alemán, portugués de Brasil, italiano, ruso, árabe (derecha a izquierda) e hindi. Sigue el sistema o fija un idioma en Ajustes."),
            ("¿Para qué la cámara?", "Solo si eliges hacer una foto para un patrón. Esa foto también se procesa en el dispositivo. No usa ubicación, micrófono, contactos ni seguimiento."),
            ("¿Funciona sin red?", "Sí. El trabajo central es totalmente sin conexión. Solo hace falta red para abrir este sitio o enviar correo. La app no contacta un servidor del desarrollador."),
            ("¿Es gratis?", "Sí. Gratis en el App Store, sin compras, suscripciones ni cuentas. Ábrela y empieza."),
            ("¿Va en iPad o Mac?", "Está hecha para iPhone con iOS 17 o posterior. iPad, Mac y Apple Vision Pro no son destinos del App Store. Descárgala en iPhone."),
            ("¿Quién la hace?", "Shanghai Qishan Cultural Communication Co., Ltd. Correo: 281916057@qq.com."),
        ],
    },
    "privacy": {
        "title": "Política de privacidad · Fuse Beads",
        "description": "Fuse Beads no recopila datos. Fotos, patrones y progreso se quedan en el iPhone. Sin cuenta, anuncios, analítica ni sincronización en la nube.",
        "lead": "Esta política describe qué hace Fuse Beads con los datos. La app está en el App Store. No recopila datos y no envía tu contenido a un servidor del desarrollador.",
        "updated": "Última actualización: 18 de septiembre de 2026. Las prácticas coinciden con el texto público del 17 de septiembre de 2026. Esta edición indica que la app está publicada, deja la política en páginas indexables y señala que el sitio no usa cookies.",
        "toc_label": "En esta página",
        "toc": [
            ("#collect", "Qué recopilamos"),
            ("#photos", "Fotos y cámara"),
            ("#storage", "Almacenamiento local"),
            ("#share", "Fotos y compartir"),
            ("#controls", "Tus controles"),
            ("#children", "Menores"),
            ("#third", "Terceros"),
            ("#contact", "Actualizaciones y contacto"),
        ],
        "sections": [
            ("collect", "Qué recopilamos", "Nada. El desarrollador no recopila fotos, patrones, listas de materiales, progreso ni registros de uso. No hay cuenta, publicidad, SDK de analítica, informe de fallos, sincronización en la nube ni seguimiento entre apps. La etiqueta de privacidad del App Store dice que no recopilamos datos de esta app. El manifiesto no lista tipos recopilados. UserDefaults solo guarda el fin de la bienvenida y el idioma."),
            ("photos", "Fotos y cámara", "Las fotos de la biblioteca o Archivos, o las tomadas con la cámara del sistema, se usan solo en el dispositivo para crear patrones. Si la limpieza de fondo está activa, Apple Vision encuentra y protege el motivo en el dispositivo. Fotos y máscaras no van a Apple, al desarrollador ni a ningún servidor. La app guarda una vista previa comprimida aparte en su contenedor para editar y copiar."),
            ("storage", "Almacenamiento local y retención", "Metadatos, celdas, marcas de material, progreso y vistas previas comprimidas permanecen en Application Support/BeadTime dentro del entorno aislado hasta que borres un proyecto, todos los proyectos o la app. Puedes exportar copia, PNG o PDF en cualquier momento. Los datos no válidos se aíslan y no sobrescriben otros proyectos."),
            ("share", "Guardar en Fotos y compartir", "Al pulsar Guardar PNG en Fotos, la app pide acceso solo para añadir y escribe el export elegido. No usa ese permiso para leer la biblioteca. Otros exports salen solo por la hoja de compartir y el destino que elijas. El selector del sistema y ese destino no son recopilación del desarrollador."),
            ("controls", "Tus controles", "Puedes dar solo las fotos elegidas, borrar proyectos o todos los datos locales y exportar copias. Este sitio es estático y de solo lectura. No pide inicio de sesión ni usa formularios, cookies, analítica, anuncios ni base de datos. El idioma va en la dirección. El buzón de soporte solo recibe lo que envías."),
            ("children", "Menores e información sensible", "La app no crea cuentas infantiles ni pide nombre, contacto u otros datos sensibles. La edad sugerida es 4+ y las familias pueden usarla juntas. No importes una foto cuyo contenido no quieras guardar en un proyecto local. No está diseñada para recopilar datos personales de menores."),
            ("third", "Terceros y servidores", "No hay SDK de terceros en tiempo de ejecución ni backend del desarrollador. La limpieza de fondo usa Vision, incluido en iOS, en el dispositivo. Alojado como se documenta, este sitio no incluye scripts de analítica ni anuncios. El correo lo gestiona el proveedor que uses para escribir."),
            ("contact", "Actualizaciones y contacto", "Si las prácticas cambian de forma material, actualizaremos esta política y su fecha. Desarrollador: Shanghai Qishan Cultural Communication Co., Ltd. Preguntas: 281916057@qq.com."),
        ],
    },
}

IT = {
    "chrome": {
        "brand_zh": "拼豆时光",
        "brand_en": "Fuse Beads",
        "nav_home": "Home",
        "nav_support": "Supporto",
        "nav_privacy": "Privacy",
        "nav_open": "Apri il menu",
        "nav_close": "Chiudi il menu",
        "nav_aria": "Navigazione principale",
        "skip": "Vai al contenuto",
        "lang_aria": "Lingua",
        "cta_store": "Scarica sull’App Store",
        "footer_explore": "Esplora",
        "footer_help": "Aiuto",
        "footer_legal": "Note legali",
        "footer_copy": "2026 Shanghai Qishan Cultural Communication Co., Ltd. 拼豆时光 / Fuse Beads. I colori a schermo sono approssimati. Perler, Hama e Artkal sono marchi dei rispettivi titolari.",
        "lost_title": "Nessuna perlina in questa pagina",
        "lost_body": "Questo indirizzo non è nella scatola. Torna al sito, al supporto o all’informativa privacy.",
        "lost_home": "Torna alla home",
    },
    "home": {
        "title": "Fuse Beads: app offline per perline da stirare sull’App Store",
        "description": "Fuse Beads: Pattern Maker è sull’App Store. Trasforma una foto in uno schema da stirare sull’iPhone. Modifica perla per perla, conta i materiali, segui colore per colore, esporta PNG o PDF. Gratis. Senza account. Senza raccolta dati.",
        "live": "Sull’App Store",
        "hero_title": "Metti l’idea sulla tavola",
        "hero_lede": "Fuse Beads è un’app iPhone completamente offline per schemi di perline da stirare. Scegli una foto o un disegno incluso, crea uno schema modificabile su questo telefono, prepara le perline e finisci colore per colore.",
        "cta_how": "Vedi il percorso",
        "meta1": "Nessun account",
        "meta2": "iOS 17 o successivo",
        "meta3": "Gratis, senza acquisti in-app",
        "def_title": "Che cos’è questa app",
        "def_body": "Fuse Beads: Pattern Maker è un’app iPhone di Shanghai Qishan Cultural Communication Co., Ltd. Il nome cinese è 拼豆时光. Apple ID 6799906107. Bundle ID com.weizhichao.beadday. Trasforma una foto da Foto, fotocamera o File in uno schema per una tavola vera e include 24 disegni originali. Generazione, modifica, materiali, seguito e backup restano sul dispositivo. Non raccoglie dati, non contatta un server dello sviluppatore e non ha pubblicità né SDK di analisi.",
        "story_title": "Uno schema che si può stirare",
        "story_body": "Scegli misura, limite di colori e una palette Perler, Hama o Artkal. L’abbinamento avviene sul dispositivo con differenza di colore percettiva e cura dei bordi. Poi modifichi perla per perla, controlli i conteggi e segni i progressi per colore.",
        "story_alt": "Tavola corgi, pinzette, ciotola e vassoio ordinato su lino",
        "loop_title": "Da un’immagine a una tavola",
        "loop1_title": "Foto o disegno incluso",
        "loop1_body": "Usa il selettore di sistema, la fotocamera o File, oppure parti da 24 disegni originali. Il ritaglio quadrato supporta zoom e spostamento. La rimozione intelligente dello sfondo resta spenta finché non la attivi. Apple Vision protegge allora il soggetto sul dispositivo.",
        "loop2_title": "Modifica finché è realizzabile",
        "loop2_body": "Tocca per ricolorare, cancella le celle vuote, annulla fino a 30 passi, ingrandisci e salta a riga o colonna. L’elenco materiali copre conteggi, spunte pronte, stima confezioni e una lista della spesa copiabile.",
        "loop2_alt": "Schema di gatto modificato perla per perla",
        "loop3_title": "Segui per colore, poi esporta",
        "loop3_body": "Evidenzia un colore, spunta le perline posate, vedi i progressi e il successivo. Esporta PNG o PDF con coordinate. Le tavole grandi si dividono in pagine 20×20. Una foto finita può restare nel progetto locale.",
        "loop3_alt": "Schema di margherita per il seguito",
        "spec_title": "Misure di tavole vere",
        "spec_body": "Il punto di partenza usuale è 40×40 con 16 colori. I piccoli charms stanno in 15×15 o 21×21. Rettangoli e misure personalizzate tengono il ritaglio allineato alla tavola.",
        "spec_boards": "Tavole",
        "spec_boards_val": "15, 21, 29, 40, 58, più personalizzato",
        "spec_colors": "Limite colori",
        "spec_colors_val": "8, 12, 16 o 24 colori",
        "spec_library": "Schemi inclusi",
        "spec_library_val": "24 disegni originali",
        "spec_locales": "Lingue",
        "spec_locales_val": "13 lingue, arabo RTL incluso",
        "spec_export": "Esporta",
        "spec_export_val": "PNG e PDF con coordinate",
        "pal_title": "I codici colore sono riferimenti a schermo",
        "pal_body": "Nomi Perler, numeri Hama Midi e Artkal S-5mm aiutano a scegliere una palette approssimata. I marchi appartengono ai titolari. Questa app non è affiliata, sponsorizzata né ufficialmente autorizzata. Controlla la cartella colori fisica aggiornata prima di un acquisto grande.",
        "pal_perler": "Nomi Perler",
        "pal_hama": "Numeri Hama Midi",
        "pal_artkal": "Numeri Artkal S-5mm",
        "locale_title": "L’interfaccia ti segue",
        "locale_body": "Interfaccia, testi dei permessi e testi legali seguono la lingua di sistema o una lingua bloccata in Impostazioni. L’arabo va da destra a sinistra. Questo sito ha un indirizzo distinto per lingua, così si può cercare e citare la pagina giusta.",
        "off_title": "Resta su questo iPhone",
        "off1_title": "Nulla viene raccolto",
        "off1_body": "Niente account, pubblicità, SDK di analisi o tracciamento. L’app non carica foto o progetti su un server dello sviluppatore.",
        "off2_title": "Lavoro sul dispositivo",
        "off2_body": "Quantizzazione, sfondo, anteprime e backup vivono nel contenitore dell’app. Disinstallare cancella gli schemi locali: esporta prima un backup in Impostazioni.",
        "off3_title": "Scegli tu cosa esce",
        "off3_body": "I file escono solo se salvi un PNG in Foto o scegli una destinazione dal foglio di condivisione.",
        "cta_title": "La prima tavola sul tavolo",
        "cta_body": "Gratis ora sull’App Store. Nessuna registrazione. Apri l’app e trasforma una foto in uno schema realizzabile.",
    },
    "support": {
        "title": "Supporto · Fuse Beads",
        "description": "Aiuto per Fuse Beads sull’App Store: import foto, generazione, materiali, seguito, backup, export e come scrivere. L’app è offline e non raccoglie dati.",
        "lead": "Parti dalle domande del flusso reale. Se serve ancora aiuto, scrivi e incolla il testo diagnostico dell’app.",
        "contact_title": "Contatta il supporto",
        "contact_body": "Non c’è un sistema di ticket né un tempo di risposta promesso. Questa pagina e la casella sono la stessa porta.",
        "contact_mail": "Email di supporto",
        "contact_include": "Includi",
        "contact1": "Versione dell’app da Impostazioni",
        "contact2": "Modello iPhone e versione iOS",
        "contact3": "Passi per riprodurre",
        "contact4": "Testo diagnostico copiato in Impostazioni",
        "contact_note": "Non allegare foto originali con contenuti privati. La diagnostica omette foto e schemi.",
        "guides_title": "Come fare una tavola",
        "g1_title": "Trasformare una foto in schema",
        "g1_body": "In Home avvia un progetto foto e scegli un’immagine da Foto, fotocamera o File. Imposta ritaglio, misura, limite colori, dettaglio e palette. Un avvio attento è 40×40 con 16 colori. Lascia spenta la rimozione dello sfondo salvo soggetto chiaro e sfondo fastidioso. Guarda l’anteprima, genera, confronta con l’originale o torna indietro.",
        "g2_title": "Contare i materiali e comprare",
        "g2_body": "In Materiali vedi i conteggi per colore. Spunta i colori che hai, stima le confezioni e copia la lista. I codici a schermo sono approssimati. Controlla la cartella fisica aggiornata del marchio prima di un acquisto grande.",
        "g3_title": "Seguire colore per colore",
        "g3_body": "In Segui scegli un colore: solo quello viene evidenziato. Tocca le perline posate, vedi il completamento e il successivo. Tieni lo schermo acceso se serve. I progressi restano nel progetto locale.",
        "g4_title": "Esportare e fare backup",
        "g4_body": "Esporta PNG o PDF con coordinate dallo spazio di lavoro o dal menu del progetto. Le tavole grandi come 58×58 hanno pagine 20×20. Prima di cambiare telefono o cancellare l’app, esporta un backup JSON da Io → Impostazioni e privacy. Disinstallare cancella tutti gli schemi nella sandbox.",
        "faq_title": "Domande frequenti",
        "download_title": "Dove scaricare",
        "download_body": "Fuse Beads: Pattern Maker è sull’App Store per iPhone, iOS 17 o successivo. Gratis, senza acquisti in-app né abbonamenti. In vendita in 175 paesi o regioni.",
        "faqs": [
            ("Le foto vengono caricate?", "No. Le foto del selettore, della fotocamera o di File si elaborano solo sul dispositivo. La rimozione dello sfondo usa Apple Vision sul dispositivo. Foto e maschere non vanno su un server."),
            ("Perché lo schema sembra sbagliato?", "Dipende da nitidezza, ritaglio, misura, limite colori e dettaglio. Il percorso usuale è 40×40 con 16 colori. Usa l’anteprima, conferma sull’originale o torna indietro. Dopo il salvataggio puoi anche rigenerare dall’originale."),
            ("Come funziona la rimozione dello sfondo?", "È spenta di default. Attivata, protegge il soggetto sul dispositivo e tratta lo sfondo connesso come celle vuote. Se i bordi spariscono o resta lo sfondo, spegnila e modifica a mano, o usa una foto più chiara."),
            ("Posso comprare dai codici a schermo?", "Sono riferimenti approssimati, non colori di fabbrica. Display e lotti variano. Confronta la cartella fisica aggiornata prima di un acquisto grande."),
            ("Dove vanno PNG e PDF?", "Esporta dallo spazio di lavoro o dal menu del progetto. Il PNG si può salvare in Foto con accesso solo aggiunta; l’app non legge la libreria con quel permesso. I PDF hanno coordinate. Le tavole grandi come 58×58 aggiungono pagine 20×20. Il resto usa il foglio di condivisione."),
            ("Un progetto manca o non si apre.", "I dati sono in Application Support/BeadTime. Gli elementi danneggiati sono isolati come projects-invalid, il resto si apre. Esporta prima un backup. Se il file libreria è troppo grande, l’originale viene messo da parte e non sovrascritto."),
            ("Come si uniscono i backup?", "Impostazioni esporta un backup JSON versionato e lo importa con unione. Per lo stesso progetto vince l’orario di aggiornamento più recente. Un backup di un’app più nuova non si importa. File troppo grandi o troppi progetti vengono rifiutati."),
            ("Disinstallando restano gli schemi?", "No. Cancella schemi, anteprime e progressi della sandbox. Esporta un backup locale prima di togliere l’app o cambiare telefono."),
            ("Come copio la diagnostica?", "Io → Impostazioni e privacy → Copia informazioni diagnostiche. Include versione, dispositivo, sistema e numero di progetti locali, non foto o schemi. Incollalo nella mail di supporto."),
            ("Quali lingue ci sono?", "Inglese, cinese semplificato, cinese tradizionale, giapponese, coreano, spagnolo, francese, tedesco, portoghese brasiliano, italiano, russo, arabo (destra-sinistra) e hindi. Segui il sistema o blocca una lingua in Impostazioni."),
            ("Perché la fotocamera?", "Solo se scegli di scattare per uno schema. Anche quella foto si elabora sul dispositivo. Non usa posizione, microfono, contatti o tracciamento."),
            ("Funziona senza rete?", "Sì. Il lavoro centrale è offline. Serve rete solo per aprire questo sito o inviare email. L’app non contatta un server dello sviluppatore."),
            ("L’app è gratis?", "Sì. Gratis sull’App Store, senza acquisti, abbonamenti o account. Aprila e inizia."),
            ("Va su iPad o Mac?", "È per iPhone con iOS 17 o successivo. iPad, Mac e Apple Vision Pro non sono destinazioni App Store. Scaricala su iPhone."),
            ("Chi la realizza?", "Shanghai Qishan Cultural Communication Co., Ltd. Email: 281916057@qq.com."),
        ],
    },
    "privacy": {
        "title": "Informativa privacy · Fuse Beads",
        "description": "Fuse Beads non raccoglie dati. Foto, schemi e progressi restano sull’iPhone. Niente account, pubblicità, analisi o sync cloud.",
        "lead": "Questa informativa descrive cosa fa davvero Fuse Beads con i dati. L’app è sull’App Store. Non raccoglie dati e non invia i tuoi contenuti a un server dello sviluppatore.",
        "updated": "Ultimo aggiornamento: 18 settembre 2026. Le pratiche coincidono con il testo pubblico del 17 settembre 2026. Questa edizione precisa che l’app è online, pubblica l’informativa in pagine indicizzabili e indica che il sito non usa cookie.",
        "toc_label": "In questa pagina",
        "toc": [
            ("#collect", "Cosa raccogliamo"),
            ("#photos", "Foto e fotocamera"),
            ("#storage", "Archiviazione locale"),
            ("#share", "Foto e condivisione"),
            ("#controls", "I tuoi controlli"),
            ("#children", "Minori"),
            ("#third", "Terze parti"),
            ("#contact", "Aggiornamenti e contatti"),
        ],
        "sections": [
            ("collect", "Cosa raccogliamo", "Niente. Lo sviluppatore non raccoglie foto, schemi, liste materiali, progressi o registri d’uso. Non ci sono account, pubblicità, SDK di analisi, report di crash, sync cloud o tracciamento tra app. L’etichetta privacy dell’App Store dice che non raccogliamo dati da questa app. Il manifesto non elenca tipi raccolti. UserDefaults memorizza solo il completamento della guida e la lingua."),
            ("photos", "Foto e fotocamera", "Le foto da libreria o File, o scattate con la fotocamera di sistema, servono solo sul dispositivo a creare schemi. Se la rimozione dello sfondo è attiva, Apple Vision trova e protegge il soggetto sul dispositivo. Foto e maschere non vanno ad Apple, allo sviluppatore o a un server. L’app tiene un’anteprima compressa distinta nel contenitore per modifica e backup."),
            ("storage", "Archiviazione locale e conservazione", "Metadati, celle, spunte materiali, progressi e anteprime compressi restano in Application Support/BeadTime nella sandbox finché non elimini un progetto, tutti i progetti o l’app. Puoi esportare backup, PNG o PDF in qualsiasi momento. I dati non validi sono isolati e non sovrascrivono altri progetti."),
            ("share", "Salvataggio in Foto e condivisione", "Toccando Salva PNG in Foto, l’app chiede accesso solo aggiunta e scrive l’export scelto. Non usa quel permesso per leggere la libreria. Altri export escono solo tramite il foglio di condivisione e la destinazione scelta. Il selettore di sistema e quella destinazione non sono raccolta dello sviluppatore."),
            ("controls", "I tuoi controlli", "Puoi fornire solo le foto scelte, eliminare progetti o tutti i dati locali ed esportare backup. Questo sito è statico in sola lettura. Non chiede accesso e non usa moduli, cookie, analisi, annunci o database. La lingua sta nell’indirizzo. La casella di supporto riceve solo ciò che invii."),
            ("children", "Minori e dati sensibili", "L’app non crea account per bambini e non chiede nome, contatti o altri dati sensibili. L’età suggerita è 4+ e le famiglie possono usarla insieme. Non importare una foto il cui contenuto non vuoi conservare in un progetto locale. Non è progettata per raccogliere dati personali di minori."),
            ("third", "Terze parti e server", "Nessun SDK di terze parti a runtime e nessun backend dello sviluppatore. La rimozione dello sfondo usa Vision, incluso in iOS, sul dispositivo. Ospitato come documentato, questo sito non include script di analisi o annunci. La posta è gestita dal fornitore che usi per scrivere."),
            ("contact", "Aggiornamenti e contatti", "Se le pratiche cambiano in modo sostanziale, aggiorneremo questa informativa e la data. Sviluppatore: Shanghai Qishan Cultural Communication Co., Ltd. Domande: 281916057@qq.com."),
        ],
    },
}

PT = {
    "chrome": {
        "brand_zh": "拼豆时光",
        "brand_en": "Fuse Beads",
        "nav_home": "Início",
        "nav_support": "Suporte",
        "nav_privacy": "Privacidade",
        "nav_open": "Abrir menu",
        "nav_close": "Fechar menu",
        "nav_aria": "Navegação principal",
        "skip": "Ir ao conteúdo",
        "lang_aria": "Idioma",
        "cta_store": "Baixar na App Store",
        "footer_explore": "Explorar",
        "footer_help": "Ajuda",
        "footer_legal": "Legal",
        "footer_copy": "2026 Shanghai Qishan Cultural Communication Co., Ltd. 拼豆时光 / Fuse Beads. Cores da tela são aproximações. Perler, Hama e Artkal são marcas de seus titulares.",
        "lost_title": "Não há contas nesta página",
        "lost_body": "Esse endereço não está na caixa. Volte ao site, ao suporte ou à política de privacidade.",
        "lost_home": "Voltar ao início",
    },
    "home": {
        "title": "Fuse Beads: app offline de contas de passar na App Store",
        "description": "Fuse Beads: Pattern Maker está na App Store. Transforme uma foto em um padrão que dá para passar no iPhone. Edite conta por conta, conte materiais, siga cor por cor, exporte PNG ou PDF. Grátis. Sem conta. Sem coleta de dados.",
        "live": "Na App Store",
        "hero_title": "Coloque a ideia no tabuleiro",
        "hero_lede": "Fuse Beads é um app de iPhone totalmente offline para padrões de contas que derretem. Escolha uma foto ou um desenho incluso, gere um padrão editável neste telefone, prepare as contas e termine cor por cor.",
        "cta_how": "Ver o percurso",
        "meta1": "Sem conta",
        "meta2": "iOS 17 ou posterior",
        "meta3": "Grátis, sem compras no app",
        "def_title": "O que é este app",
        "def_body": "Fuse Beads: Pattern Maker é um app de iPhone da Shanghai Qishan Cultural Communication Co., Ltd. O nome chinês é 拼豆时光. Apple ID 6799906107. Bundle ID com.weizhichao.beadday. Transforma uma foto de Fotos, da câmera ou de Arquivos em um padrão para um tabuleiro real e inclui 24 desenhos originais. Geração, edição, materiais, acompanhamento e backups ficam no aparelho. Não coleta dados, não fala com servidor do desenvolvedor e não tem anúncios nem SDK de análise.",
        "story_title": "Um padrão que dá para passar",
        "story_body": "Você escolhe tamanho, limite de cores e uma paleta Perler, Hama ou Artkal. A combinação acontece no aparelho com diferença de cor perceptiva e cuidado das bordas. Depois edita conta por conta, confere as quantidades e marca o progresso por cor.",
        "story_alt": "Tabuleiro de corgi, pinça, tigela e bandeja organizada sobre linho",
        "loop_title": "De uma imagem a um tabuleiro",
        "loop1_title": "Foto ou desenho incluso",
        "loop1_body": "Use o seletor do sistema, a câmera ou Arquivos, ou comece com 24 desenhos originais. O recorte quadrado aceita zoom e deslocamento. A limpeza inteligente de fundo fica desligada até você ligar. O Apple Vision então protege o assunto no aparelho.",
        "loop2_title": "Editar até dar para montar",
        "loop2_body": "Toque para recolorir, apague células vazias, desfaça até 30 passos, amplie e pule para linha ou coluna. A lista de materiais cobre totais, marcas de pronto, estimativa de pacotes e uma lista de compras copiável.",
        "loop2_alt": "Padrão de gato editado conta por conta",
        "loop3_title": "Seguir por cor e exportar",
        "loop3_body": "Destaque uma cor, marque contas colocadas e veja o progresso e a próxima. Exporte PNG ou PDF com coordenadas. Tabuleiros grandes se dividem em páginas 20×20. Uma foto pronta pode ficar no projeto local.",
        "loop3_alt": "Padrão de margarida para acompanhar",
        "spec_title": "Tamanhos de tabuleiros reais",
        "spec_body": "O ponto de partida usual é 40×40 com 16 cores. Charms pequenos cabem em 15×15 ou 21×21. Retângulos e medidas próprias mantêm o recorte alinhado ao tabuleiro.",
        "spec_boards": "Tabuleiros",
        "spec_boards_val": "15, 21, 29, 40, 58, mais personalizado",
        "spec_colors": "Limite de cores",
        "spec_colors_val": "8, 12, 16 ou 24 cores",
        "spec_library": "Padrões inclusos",
        "spec_library_val": "24 desenhos originais",
        "spec_locales": "Idiomas",
        "spec_locales_val": "13 idiomas, árabe RTL incluso",
        "spec_export": "Exportar",
        "spec_export_val": "PNG e PDF com coordenadas",
        "pal_title": "Os códigos são referência na tela",
        "pal_body": "Nomes Perler, números Hama Midi e Artkal S-5mm ajudam a escolher uma paleta aproximada. Essas marcas pertencem aos titulares. Este app não é afiliado, patrocinado nem oficialmente autorizado. Confira a carta física atual antes de comprar em quantidade.",
        "pal_perler": "Nomes Perler",
        "pal_hama": "Números Hama Midi",
        "pal_artkal": "Números Artkal S-5mm",
        "locale_title": "A interface segue você",
        "locale_body": "Interface, textos de permissão e textos legais seguem o idioma do sistema ou um idioma fixado em Ajustes. O árabe vai da direita para a esquerda. Este site tem um endereço distinto por idioma para busca e citação.",
        "off_title": "Fica neste iPhone",
        "off1_title": "Nada coletado",
        "off1_body": "Sem contas, anúncios, SDK de análise ou rastreamento. O app não envia fotos ou projetos a um servidor do desenvolvedor.",
        "off2_title": "Trabalho no aparelho",
        "off2_body": "Quantização, fundo, prévias e backups vivem no recipiente do app. Desinstalar apaga padrões locais: exporte antes um backup em Ajustes.",
        "off3_title": "Você escolhe o que sai",
        "off3_body": "Os arquivos saem só quando você salva um PNG em Fotos ou escolhe um destino na folha de compartilhamento.",
        "cta_title": "O primeiro tabuleiro na mesa",
        "cta_body": "Grátis agora na App Store. Sem cadastro. Abra o app e transforme uma foto em um padrão que dá para montar.",
    },
    "support": {
        "title": "Suporte · Fuse Beads",
        "description": "Ajuda do Fuse Beads na App Store: importar foto, gerar, materiais, acompanhar, backup, exportar e como escrever. O app é offline e não coleta dados.",
        "lead": "Comece pelas perguntas do fluxo real. Se ainda precisar de ajuda, escreva e cole o texto de diagnóstico do app.",
        "contact_title": "Falar com o suporte",
        "contact_body": "Não há sistema de tickets nem prazo de resposta. Esta página e a caixa de e-mail são a mesma porta.",
        "contact_mail": "E-mail de suporte",
        "contact_include": "Inclua",
        "contact1": "Versão do app em Ajustes",
        "contact2": "Modelo do iPhone e versão do iOS",
        "contact3": "Passos para reproduzir",
        "contact4": "Texto de diagnóstico copiado em Ajustes",
        "contact_note": "Não anexe fotos originais com conteúdo privado. O diagnóstico omite fotos e padrões.",
        "guides_title": "Como fazer um tabuleiro",
        "g1_title": "Transformar uma foto em padrão",
        "g1_body": "No Início, comece um projeto de foto e escolha uma imagem em Fotos, câmera ou Arquivos. Ajuste recorte, tamanho, limite de cores, detalhe e paleta. Um começo cuidadoso é 40×40 com 16 cores. Deixe a limpeza de fundo desligada salvo assunto nítido e fundo no caminho. Veja a prévia, gere, compare com o original ou volte a ajustar.",
        "g2_title": "Contar materiais e comprar",
        "g2_body": "Em Materiais você vê totais por cor. Marque as que já tem, estime pacotes e copie a lista. Os códigos da tela são aproximados. Confira a carta física atual da marca antes de uma compra grande.",
        "g3_title": "Acompanhar cor por cor",
        "g3_body": "Em Seguir, escolha uma cor para destacá-la só. Toque nas contas colocadas, veja o avanço e a próxima. Mantenha a tela ligada se precisar. O progresso fica no projeto local.",
        "g4_title": "Exportar e fazer backup",
        "g4_body": "Exporte PNG ou PDF com coordenadas do espaço de trabalho ou do menu do projeto. Tabuleiros grandes como 58×58 incluem páginas 20×20. Antes de trocar de telefone ou apagar o app, exporte um backup JSON em Eu → Ajustes e privacidade. Desinstalar apaga todos os padrões da sandbox.",
        "faq_title": "Perguntas frequentes",
        "download_title": "Onde baixar",
        "download_body": "Fuse Beads: Pattern Maker está na App Store para iPhone, iOS 17 ou posterior. Grátis, sem compras no app nem assinaturas. Vendido em 175 países ou regiões.",
        "faqs": [
            ("Minhas fotos são enviadas?", "Não. Fotos do seletor, da câmera ou de Arquivos são processadas só no aparelho. A limpeza de fundo usa Apple Vision no aparelho. Fotos e máscaras não vão a um servidor."),
            ("Por que o padrão parece errado?", "Depende da nitidez, do recorte, do tamanho, do limite de cores e do detalhe. O caminho usual é 40×40 com 16 cores. Use a prévia, confirme no original ou volte. Depois de salvar também pode gerar de novo a partir do original."),
            ("Como funciona a limpeza de fundo?", "Vem desligada. Ligada, protege o assunto no aparelho e trata o fundo ligado como células vazias. Se as bordas sumirem ou o fundo ficar, desligue e edite à mão, ou use uma foto mais nítida."),
            ("Posso comprar pelos códigos da tela?", "São referências aproximadas, não cores de fábrica. Telas e lotes variam. Compare a carta física atual antes de uma compra grande."),
            ("Para onde vão PNG e PDF?", "Exporte do espaço de trabalho ou do menu do projeto. O PNG pode ir para Fotos com acesso só de adicionar; o app não lê a biblioteca com essa permissão. PDFs têm coordenadas. Tabuleiros grandes como 58×58 ganham páginas 20×20. O resto usa a folha de compartilhamento."),
            ("Um projeto sumiu ou não abre.", "Os dados ficam em Application Support/BeadTime. Itens danificados são isolados como projects-invalid e o resto abre. Exporte um backup primeiro. Se o arquivo da biblioteca for grande demais, o original é afastado e não é sobrescrito."),
            ("Como os backups se misturam?", "Ajustes exporta um backup JSON versionado e importa com mesclagem. No mesmo projeto vence o horário de atualização mais novo. Backup de um app mais novo não entra. Arquivos grandes demais ou projetos demais são recusados."),
            ("Desinstalar guarda os padrões?", "Não. Apaga padrões, prévias e progresso da sandbox. Exporte um backup local antes de remover o app ou trocar de telefone."),
            ("Como copio o diagnóstico?", "Eu → Ajustes e privacidade → Copiar informações de diagnóstico. Inclui versão, aparelho, sistema e número de projetos locais, sem fotos nem padrões. Cole no e-mail de suporte."),
            ("Quais idiomas entram?", "Inglês, chinês simplificado, chinês tradicional, japonês, coreano, espanhol, francês, alemão, português do Brasil, italiano, russo, árabe (direita para a esquerda) e hindi. Siga o sistema ou fixe um idioma em Ajustes."),
            ("Para que a câmera?", "Só se você escolher tirar uma foto para um padrão. Essa foto também é processada no aparelho. Não usa localização, microfone, contatos nem rastreamento."),
            ("Funciona sem rede?", "Sim. O trabalho central é offline. A rede só serve para abrir este site ou enviar e-mail. O app não fala com servidor do desenvolvedor."),
            ("O app é grátis?", "Sim. Grátis na App Store, sem compras, assinaturas ou contas. Abra e comece."),
            ("Roda no iPad ou Mac?", "É para iPhone com iOS 17 ou posterior. iPad, Mac e Apple Vision Pro não são destinos da App Store. Baixe no iPhone."),
            ("Quem faz o app?", "Shanghai Qishan Cultural Communication Co., Ltd. E-mail: 281916057@qq.com."),
        ],
    },
    "privacy": {
        "title": "Política de privacidade · Fuse Beads",
        "description": "Fuse Beads não coleta dados. Fotos, padrões e progresso ficam no iPhone. Sem conta, anúncios, análise ou sync na nuvem.",
        "lead": "Esta política descreve o que o Fuse Beads realmente faz com dados. O app está na App Store. Não coleta dados e não envia seu conteúdo a um servidor do desenvolvedor.",
        "updated": "Última atualização: 18 de setembro de 2026. As práticas coincidem com o texto público de 17 de setembro de 2026. Esta edição diz que o app está no ar, publica a política em páginas indexáveis e nota que o site não usa cookies.",
        "toc_label": "Nesta página",
        "toc": [
            ("#collect", "O que coletamos"),
            ("#photos", "Fotos e câmera"),
            ("#storage", "Armazenamento local"),
            ("#share", "Fotos e compartilhar"),
            ("#controls", "Seus controles"),
            ("#children", "Crianças"),
            ("#third", "Terceiros"),
            ("#contact", "Atualizações e contato"),
        ],
        "sections": [
            ("collect", "O que coletamos", "Nada. O desenvolvedor não coleta fotos, padrões, listas de materiais, progresso nem registros de uso. Não há conta, anúncio, SDK de análise, relatório de falha, sync na nuvem nem rastreamento entre apps. O rótulo da App Store diz que não coletamos dados deste app. O manifesto não lista tipos coletados. UserDefaults só guarda o fim da introdução e o idioma."),
            ("photos", "Fotos e câmera", "Fotos da biblioteca ou de Arquivos, ou capturadas com a câmera do sistema, servem só no aparelho para montar padrões. Se a limpeza de fundo estiver ligada, o Apple Vision acha e protege o assunto no aparelho. Fotos e máscaras não vão à Apple, ao desenvolvedor nem a qualquer servidor. O app guarda uma prévia compactada à parte no recipiente para editar e fazer backup."),
            ("storage", "Armazenamento local e retenção", "Metadados, células, marcas de material, progresso e prévias compactadas ficam em Application Support/BeadTime na sandbox até você apagar um projeto, todos os projetos ou o app. Você pode exportar backup, PNG ou PDF a qualquer momento. Dados inválidos são isolados e não sobrescrevem outros projetos."),
            ("share", "Salvar em Fotos e compartilhar", "Ao tocar em Salvar PNG em Fotos, o app pede acesso só de adicionar e grava o export escolhido. Não usa essa permissão para ler a biblioteca. Outros exports saem só pela folha de compartilhamento e o destino que você escolher. O seletor do sistema e esse destino não são coleta do desenvolvedor."),
            ("controls", "Seus controles", "Você pode fornecer só as fotos escolhidas, apagar projetos ou todos os dados locais e exportar backups. Este site é estático e só leitura. Não pede login e não usa formulários, cookies, análise, anúncios nem banco. O idioma vem do endereço. A caixa de suporte só recebe o que você envia."),
            ("children", "Crianças e dados sensíveis", "O app não cria contas infantis e não pede nome, contato nem outros dados sensíveis. A faixa sugerida é 4+ e famílias podem usar juntas. Não importe uma foto cujo conteúdo você não queira guardar num projeto local. Não foi feito para coletar dados pessoais de crianças."),
            ("third", "Terceiros e servidores", "Não há SDK de terceiros em tempo de execução nem backend do desenvolvedor. A limpeza de fundo usa o Vision incluso no iOS, no aparelho. Hospedado como documentado, este site não inclui scripts de análise ou anúncios. O e-mail passa pelo provedor que você usa para escrever."),
            ("contact", "Atualizações e contato", "Se as práticas mudarem de forma material, atualizaremos esta política e a data. Desenvolvedor: Shanghai Qishan Cultural Communication Co., Ltd. Perguntas: 281916057@qq.com."),
        ],
    },
}

RU = {
    "chrome": {
        "brand_zh": "拼豆时光",
        "brand_en": "Fuse Beads",
        "nav_home": "Главная",
        "nav_support": "Поддержка",
        "nav_privacy": "Конфиденциальность",
        "nav_open": "Открыть меню",
        "nav_close": "Закрыть меню",
        "nav_aria": "Основная навигация",
        "skip": "К содержанию",
        "lang_aria": "Язык",
        "cta_store": "Скачать в App Store",
        "footer_explore": "Смотреть",
        "footer_help": "Помощь",
        "footer_legal": "Правовое",
        "footer_copy": "2026 Shanghai Qishan Cultural Communication Co., Ltd. 拼豆时光 / Fuse Beads. Цвета на экране приблизительны. Perler, Hama и Artkal — товарные знаки правообладателей.",
        "lost_title": "На этой странице нет бусин",
        "lost_body": "Этого адреса нет в коробке. Вернитесь на сайт, в поддержку или к политике конфиденциальности.",
        "lost_home": "На главную",
    },
    "home": {
        "title": "Fuse Beads: офлайн-приложение термомозаики в App Store",
        "description": "Fuse Beads: Pattern Maker уже в App Store. Фото становится схемой термомозаики на iPhone. Правка бусина за бусиной, счёт материалов, ход по цвету, экспорт PNG или PDF. Бесплатно. Без аккаунта. Без сбора данных.",
        "live": "В App Store",
        "hero_title": "Идею на доску",
        "hero_lede": "Fuse Beads — полностью офлайн-приложение iPhone для схем термомозаики. Выберите фото или встроенный рисунок, создайте редактируемую схему на этом телефоне, подготовьте бусины и собирайте цвет за цветом.",
        "cta_how": "Смотреть процесс",
        "meta1": "Без аккаунта",
        "meta2": "iOS 17 или новее",
        "meta3": "Бесплатно, без встроенных покупок",
        "def_title": "Что это за приложение",
        "def_body": "Fuse Beads: Pattern Maker — приложение для iPhone от Shanghai Qishan Cultural Communication Co., Ltd. Китайское имя — 拼豆时光. Apple ID 6799906107. Bundle ID com.weizhichao.beadday. Оно превращает фото из «Фото», камеры или Файлов в схему для настоящей доски и содержит 24 оригинальных рисунка. Создание, правка, материалы, сборка и резервные копии остаются на устройстве. Приложение не собирает данные, не обращается к серверу разработчика и не содержит рекламы или SDK аналитики.",
        "story_title": "Схема, которую можно прогладить",
        "story_body": "Вы выбираете размер доски, предел цветов и палитру Perler, Hama или Artkal. Подбор цвета идёт на устройстве с восприятием разницы и защитой края. Затем правите бусину за бусиной, смотрите количества и отмечаете ход по цвету.",
        "story_alt": "Доска с корги, пинцет, миска и лоток на льне",
        "loop_title": "От снимка к одной доске",
        "loop1_title": "Фото или встроенный рисунок",
        "loop1_body": "Используйте системный выбор, камеру или Файлы, либо начните с 24 оригинальных рисунков. Квадратная обрезка поддерживает масштаб и сдвиг. Умная очистка фона выключена, пока вы её не включите. Тогда Apple Vision защищает объект на устройстве.",
        "loop2_title": "Править, пока можно собрать",
        "loop2_body": "Нажимайте, чтобы перекрасить, стирайте пустые ячейки, отменяйте до 30 шагов, масштабируйте, переходите к строке и столбцу. Список материалов показывает количества, готовые цвета, оценку упаковок и копируемый список покупок.",
        "loop2_alt": "Схема кота, правка по бусинам",
        "loop3_title": "Собирать по цвету и выгружать",
        "loop3_body": "Подсветите один цвет, отмечайте поставленные бусины, смотрите общий ход и следующий цвет. Выгружайте PNG или PDF с координатами. Большие доски делятся на листы 20×20. Готовое фото можно оставить в локальном проекте.",
        "loop3_alt": "Схема ромашки для сборки",
        "spec_title": "Размеры настоящих досок",
        "spec_body": "Обычная точка старта — 40×40 и 16 цветов. Мелкие мотивы входят в 15×15 или 21×21. Прямоугольники и свои размеры держат кадр обрезки по доске.",
        "spec_boards": "Доски",
        "spec_boards_val": "15, 21, 29, 40, 58 и свои размеры",
        "spec_colors": "Предел цветов",
        "spec_colors_val": "8, 12, 16 или 24 цвета",
        "spec_library": "Встроенные схемы",
        "spec_library_val": "24 оригинальных рисунка",
        "spec_locales": "Языки",
        "spec_locales_val": "13 языков, включая арабский RTL",
        "spec_export": "Экспорт",
        "spec_export_val": "PNG и PDF с координатами",
        "pal_title": "Коды цвета — экранный ориентир",
        "pal_body": "Имена Perler, номера Hama Midi и Artkal S-5mm помогают выбрать близкую палитру. Знаки принадлежат правообладателям. Приложение не аффилировано, не спонсируется и не имеет официального разрешения. Перед большой покупкой сверьтесь с актуальной физической картой.",
        "pal_perler": "Имена Perler",
        "pal_hama": "Номера Hama Midi",
        "pal_artkal": "Номера Artkal S-5mm",
        "locale_title": "Интерфейс следует за вами",
        "locale_body": "Интерфейс, тексты разрешений и правовые тексты следуют языку системы или языку в Настройках. Арабский идёт справа налево. У сайта отдельный адрес на каждый язык, чтобы поиск и цитаты попадали на нужную страницу.",
        "off_title": "Остаётся на этом iPhone",
        "off1_title": "Ничего не собираем",
        "off1_body": "Нет аккаунтов, рекламы, SDK аналитики и трекинга. Приложение не отправляет фото и проекты на сервер разработчика.",
        "off2_title": "Работа на устройстве",
        "off2_body": "Квантование, фон, превью и копии живут в контейнере приложения. Удаление стирает локальные схемы: сначала выгрузите копию в Настройках.",
        "off3_title": "Вы решаете, что уходит",
        "off3_body": "Файлы покидают приложение только если вы сохраняете PNG в «Фото» или выбираете назначение в меню «Поделиться».",
        "cta_title": "Первая доска за столом",
        "cta_body": "Сейчас бесплатно в App Store. Без регистрации. Откройте приложение и превратите фото в собираемую схему.",
    },
    "support": {
        "title": "Поддержка · Fuse Beads",
        "description": "Помощь по Fuse Beads в App Store: импорт фото, создание, материалы, сборка, копии, экспорт и как написать. Приложение офлайн и не собирает данные.",
        "lead": "Начните с вопросов из реального процесса. Если помощь всё ещё нужна, напишите и вставьте диагностический текст из приложения.",
        "contact_title": "Связаться с поддержкой",
        "contact_body": "Нет тикет-системы и обещанного срока ответа. Эта страница и почтовый ящик — одна дверь.",
        "contact_mail": "Почта поддержки",
        "contact_include": "Укажите",
        "contact1": "Версию приложения из Настроек",
        "contact2": "Модель iPhone и версию iOS",
        "contact3": "Шаги воспроизведения",
        "contact4": "Диагностический текст, скопированный в Настройках",
        "contact_note": "Не прикладывайте исходные фото с личным содержимым. Диагностика не содержит фото и схем.",
        "guides_title": "Как собрать доску",
        "g1_title": "Сделать схему из фото",
        "g1_body": "На главной начните проект из фото и выберите снимок из «Фото», камеры или Файлов. Настройте обрезку, размер, предел цветов, режим деталей и палитру. Аккуратный старт — 40×40 и 16 цветов. Оставьте умную очистку фона выключенной, если объект неясен или фон не мешает. Смотрите живое превью, создайте схему, сравните с оригиналом или вернитесь.",
        "g2_title": "Посчитать материалы и купить",
        "g2_body": "В материалах видны количества по цветам. Отметьте то, что уже есть, оцените упаковки и скопируйте список. Экранные коды приблизительны. Перед большой покупкой сверьтесь с актуальной физической картой бренда.",
        "g3_title": "Собирать цвет за цветом",
        "g3_body": "В сборке выберите один цвет: подсветится только он. Нажимайте поставленные бусины, смотрите общий ход и следующий цвет. При необходимости оставьте экран включённым. Прогресс остаётся в локальном проекте.",
        "g4_title": "Экспорт и резервная копия",
        "g4_body": "Выгружайте PNG или PDF с координатами из рабочей области или меню проекта. Большие доски вроде 58×58 получают листы 20×20. Перед сменой телефона или удалением приложения выгрузите JSON-копию в «Я → Настройки и конфиденциальность». Удаление стирает все схемы в песочнице.",
        "faq_title": "Частые вопросы",
        "download_title": "Где скачать",
        "download_body": "Fuse Beads: Pattern Maker в App Store для iPhone, iOS 17 или новее. Бесплатно, без встроенных покупок и подписок. Продаётся в 175 странах или регионах.",
        "faqs": [
            ("Фото загружаются?", "Нет. Снимки из системного выбора, камеры или Файлов обрабатываются только на устройстве. Умная очистка фона использует Apple Vision на устройстве. Фото и маски не уходят на сервер."),
            ("Почему схема выглядит не так?", "Влияют резкость, обрезка, размер, предел цветов и режим деталей. Обычный путь качества — 40×40 и 16 цветов. Смотрите живое превью, сверяйте с оригиналом или возвращайтесь. После сохранения можно заново создать из оригинала."),
            ("Как работает умная очистка фона?", "По умолчанию выключена. Включённая защищает объект на устройстве и считает связанный фон пустыми ячейками. Если края пропадают или фон остаётся, выключите и правьте вручную либо возьмите более ясное фото."),
            ("Можно покупать по экранным кодам?", "Это приблизительные ориентиры, не заводские цвета. Экраны и партии расходятся. Перед большой покупкой сверьтесь с актуальной физической картой."),
            ("Куда деваются PNG и PDF?", "Выгрузка из рабочей области или меню проекта. PNG можно сохранить в «Фото» с правом только добавлять; приложение не читает медиатеку этим правом. В PDF есть координаты. Большие доски вроде 58×58 получают листы 20×20. Остальное идёт через системное меню «Поделиться»."),
            ("Проект пропал или не открывается.", "Данные в Application Support/BeadTime. Повреждённые элементы изолируются как projects-invalid, остальное открывается. Сначала выгрузите копию. Если файл библиотеки слишком большой, оригинал откладывается и не перезаписывается."),
            ("Как сливаются копии?", "Настройки выгружают версионированную JSON-копию и импортируют со слиянием. Для одного проекта побеждает более новое время обновления. Копия более новой версии приложения не импортируется. Слишком большие файлы или слишком много проектов отклоняются."),
            ("После удаления схемы остаются?", "Нет. Удаление стирает схемы, превью и прогресс песочницы. Выгрузите локальную копию до удаления приложения или смены телефона."),
            ("Как скопировать диагностику?", "Я → Настройки и конфиденциальность → Скопировать диагностическую информацию. Там версия, устройство, система и число локальных проектов, без фото и схем. Вставьте в письмо поддержки."),
            ("Какие языки есть?", "Английский, упрощённый китайский, традиционный китайский, японский, корейский, испанский, французский, немецкий, бразильский португальский, итальянский, русский, арабский (справа налево) и хинди. Следуйте системе или закрепите язык в Настройках."),
            ("Зачем разрешение камеры?", "Только если вы сами снимаете для схемы. Этот снимок тоже обрабатывается на устройстве. Геолокация, микрофон, контакты и трекинг не используются."),
            ("Работает без сети?", "Да. Основная работа полностью офлайн. Сеть нужна только чтобы открыть этот сайт или отправить письмо. Приложение не обращается к серверу разработчика."),
            ("Приложение бесплатное?", "Да. Бесплатно в App Store, без покупок, подписок и аккаунтов. Откройте и начинайте."),
            ("Есть iPad или Mac?", "Сделано для iPhone на iOS 17 или новее. iPad, Mac и Apple Vision Pro не являются витринами App Store. Скачивайте на iPhone."),
            ("Кто делает Fuse Beads?", "Shanghai Qishan Cultural Communication Co., Ltd. Почта: 281916057@qq.com."),
        ],
    },
    "privacy": {
        "title": "Политика конфиденциальности · Fuse Beads",
        "description": "Fuse Beads не собирает данные. Фото, схемы и прогресс остаются на iPhone. Нет аккаунта, рекламы, аналитики и облачной синхронизации.",
        "lead": "Эта политика описывает, что Fuse Beads на самом деле делает с данными. Приложение в App Store. Оно не собирает данные и не отправляет содержимое на сервер разработчика.",
        "updated": "Последнее обновление: 18 сентября 2026. Практика совпадает с публичным текстом от 17 сентября 2026. В этой редакции сказано, что приложение опубликовано, политика выложена как индексируемые страницы, а сайт не использует cookie.",
        "toc_label": "На этой странице",
        "toc": [
            ("#collect", "Что мы собираем"),
            ("#photos", "Фото и камера"),
            ("#storage", "Локальное хранение"),
            ("#share", "Фото и обмен"),
            ("#controls", "Ваш контроль"),
            ("#children", "Дети"),
            ("#third", "Третьи стороны"),
            ("#contact", "Обновления и связь"),
        ],
        "sections": [
            ("collect", "Что мы собираем", "Ничего. Разработчик не собирает из приложения фото, схемы, списки материалов, прогресс и записи использования. Нет аккаунта, рекламы, SDK аналитики, отчётов о сбоях, облачной синхронизации и межприложенческого трекинга. Ответ в App Store: мы не собираем данные из этого приложения. Манифест конфиденциальности не перечисляет типы сбора. UserDefaults хранит только завершение знакомства и язык."),
            ("photos", "Фото и камера", "Снимки из библиотеки или Файлов либо кадры системной камеры используются только на устройстве для схем. Если умная очистка фона включена, Apple Vision находит и защищает объект на устройстве. Фото и маски не уходят Apple, разработчику или на какой-либо сервер. Приложение хранит отдельное сжатое превью в контейнере для правки и копий."),
            ("storage", "Локальное хранение и срок", "Метаданные, ячейки, отметки материалов, прогресс сборки и сжатые превью остаются в Application Support/BeadTime в песочнице, пока вы не удалите проект, все проекты или приложение. Копию, PNG или PDF можно выгрузить в любой момент. Неверные данные изолируются и не перезаписывают другие проекты."),
            ("share", "Сохранение в «Фото» и обмен", "При «Сохранить PNG в Фото» приложение просит право только добавлять и пишет выбранный экспорт. Этим правом медиатека не читается. Другие экспорты покидают устройство только через меню «Поделиться» и выбранное назначение. Системный выбор и это назначение не являются сбором разработчика."),
            ("controls", "Ваш контроль", "Можно дать только выбранные фото, удалить проекты или все локальные данные и выгрузить копии. Этот сайт статический и только для чтения. Нет входа, форм, cookie, аналитики, рекламы и базы. Язык задаётся адресом страницы. Почта поддержки получает только то, что вы сами отправите."),
            ("children", "Дети и чувствительные данные", "Приложение не создаёт детские аккаунты и не спрашивает имя, контакты или иные чувствительные сведения. Рекомендуемый возраст 4+, семьи могут пользоваться вместе. Не импортируйте фото, содержимое которого не хотите хранить в локальном проекте. Приложение не предназначено для сбора персональных данных детей."),
            ("third", "Третьи стороны и серверы", "Нет стороннего runtime SDK и нет сервера разработчика. Очистка фона использует Vision из iOS на устройстве. При размещении по документации на сайте нет скриптов аналитики и рекламы. Почту обрабатывает провайдер, которым вы пишете."),
            ("contact", "Обновления и связь", "Если практика существенно изменится, мы обновим эту политику и дату. Разработчик: Shanghai Qishan Cultural Communication Co., Ltd. Вопросы: 281916057@qq.com."),
        ],
    },
}
